#
# OpenBTS-UMTS/ASN/files.cmake
#

set(asn_files_rrl
	AC-To-ASC-Mapping.c
	AC-To-ASC-MappingTable.c
	ACK-NACK-repetitionFactor.c
	AICH-Info.c
	AICH-PowerOffset.c
	AICH-TransmissionTiming.c
	ANSI-41-GlobalServiceRedirectInfo.c
	ANSI-41-NAS-Parameter.c
	ANSI-41-PrivateNeighbourListInfo.c
	ANSI-41-RAND-Information.c
	ANSI-41-UserZoneID-Information.c
	AP-AICH-ChannelisationCode.c
	AP-PreambleScramblingCode.c
	AP-Signature-VCAM.c
	AP-Signature.c
	AP-Subchannel.c
	ASCSetting-FDD.c
	ASCSetting-TDD-LCR-r4.c
	ASCSetting-TDD-r7.c
	ASCSetting-TDD.c
	AccessClassBarred.c
	AccessClassBarredList.c
	AccessServiceClass-FDD.c
	AccessServiceClass-TDD-LCR-r4.c
	AccessServiceClass-TDD-r7.c
	AccessServiceClass-TDD.c
	AccessStratumReleaseIndicator.c
	AcquisitionSatInfo.c
	AcquisitionSatInfoList.c
	ActivationTime.c
	ActiveSetUpdate-r3-IEs.c
	ActiveSetUpdate-r6-IEs.c
	ActiveSetUpdate-v4b0ext-IEs.c
	ActiveSetUpdate-v590ext-IEs.c
	ActiveSetUpdate-v690ext-IEs.c
	ActiveSetUpdate.c
	ActiveSetUpdateComplete.c
	ActiveSetUpdateFailure.c
	AddOrReconfMAC-dFlow.c
	AdditionalMeasurementID-List.c
	AdditionalPRACH-TF-and-TFCS-CCCH-IEs.c
	AdditionalPRACH-TF-and-TFCS-CCCH-List.c
	AdditionalPRACH-TF-and-TFCS-CCCH.c
	AlgorithmSpecificInfo-r4.c
	AlgorithmSpecificInfo.c
	AllocationPeriodInfo.c
	AllowedIndicator.c
	AllowedTFC-List.c
	AllowedTFI-List.c
	AlmanacSatInfo.c
	AlmanacSatInfoList.c
	Alpha.c
	Ansi-41-IDNNS.c
	AssistanceDataDelivery-r3-IEs.c
	AssistanceDataDelivery-v3a0ext.c
	AssistanceDataDelivery-v4b0ext-IEs.c
	AssistanceDataDelivery.c
	AvailableAP-Signature-VCAMList.c
	AvailableAP-SignatureList.c
	AvailableAP-SubchannelList.c
	AvailableMinimumSF-ListVCAM.c
	AvailableMinimumSF-VCAM.c
	AvailableSignatures.c
	AvailableSubChannelNumbers.c
	AverageRLC-BufferPayload.c
	AzimuthAndElevation.c
	BCC.c
	BCCH-ARFCN.c
	BCCH-BCH-Message.c
	BCCH-FACH-Message.c
	BCCH-FACH-MessageType.c
	BCCH-ModificationInfo.c
	BCCH-ModificationTime.c
	BEACON-PL-Est.c
	BLER-MeasurementResults.c
	BLER-MeasurementResultsList.c
	BLER-QualityValue.c
	BLER-TransChIdList.c
	BSIC-VerificationRequired.c
	BSIC.c
	BSICReported.c
	BackoffControlParams.c
	BadSatList.c
	BitModeRLC-SizeInfo.c
	Bler-Target.c
	BurstModeParameters.c
	BurstType.c
	C-RNTI.c
	CBS-DRX-Level1Information-extension-r6.c
	CBS-DRX-Level1Information.c
	CCTrCH-PowerControlInfo-r4.c
	CCTrCH-PowerControlInfo-r5.c
	CCTrCH-PowerControlInfo-r7.c
	CCTrCH-PowerControlInfo.c
	CD-AccessSlotSubchannel.c
	CD-AccessSlotSubchannelList.c
	CD-CA-ICH-ChannelisationCode.c
	CD-PreambleScramblingCode.c
	CD-SignatureCode.c
	CD-SignatureCodeList.c
	CDMA2000-Message.c
	CDMA2000-MessageList.c
	CDMA2000-UMTS-Frequency-List.c
	CID-InclusionInfo-r4.c
	CN-DRX-CycleLengthCoefficient.c
	CN-DomainIdentity.c
	CN-DomainInformation-v390ext.c
	CN-DomainInformation.c
	CN-DomainInformationFull.c
	CN-DomainInformationList-v390ext.c
	CN-DomainInformationList.c
	CN-DomainInformationListFull.c
	CN-DomainSysInfo.c
	CN-DomainSysInfoList.c
	CN-InformationInfo-r6.c
	CN-InformationInfo.c
	CN-InformationInfoFull.c
	CN-PagedUE-Identity.c
	COUNT-C-List.c
	COUNT-C-MSB.c
	COUNT-C.c
	COUNT-CSingle.c
	CPCH-Parameters.c
	CPCH-PersistenceLevels.c
	CPCH-PersistenceLevelsList.c
	CPCH-SetID.c
	CPCH-SetInfo.c
	CPCH-SetInfoList.c
	CPCH-StatusIndicationMode.c
	CPICH-Ec-N0.c
	CPICH-RSCP.c
	CQI-RepetitionFactor.c
	CRC-Size.c
	CSICH-PowerOffset.c
	CalculationTimeForCiphering.c
	CapabilityUpdateRequirement-r4-ext.c
	CapabilityUpdateRequirement-r4.c
	CapabilityUpdateRequirement-r5.c
	CapabilityUpdateRequirement-r7-ext.c
	CapabilityUpdateRequirement.c
	CellAccessRestriction.c
	CellAndChannelIdentity.c
	CellBarred.c
	CellChangeOrderFromUTRAN-r3-IEs.c
	CellChangeOrderFromUTRAN-v590ext-IEs.c
	CellChangeOrderFromUTRAN.c
	CellChangeOrderFromUTRANFailure-r3-IEs.c
	CellChangeOrderFromUTRANFailure.c
	CellDCH-ReportCriteria-LCR-r4.c
	CellDCH-ReportCriteria.c
	CellIdentity-PerRL-List.c
	CellIdentity.c
	CellIndividualOffset.c
	CellInfo-r4.c
	CellInfo.c
	CellInfoSI-ECN0-LCR-r4.c
	CellInfoSI-ECN0.c
	CellInfoSI-HCS-ECN0-LCR-r4.c
	CellInfoSI-HCS-ECN0.c
	CellInfoSI-HCS-RSCP-LCR-r4.c
	CellInfoSI-HCS-RSCP.c
	CellInfoSI-RSCP-LCR-r4.c
	CellInfoSI-RSCP.c
	CellMeasuredResults.c
	CellMeasurementEventResults-LCR-r4.c
	CellMeasurementEventResults.c
	CellParametersID.c
	CellReportingQuantities.c
	CellSelectReselectInfo-v590ext.c
	CellSelectReselectInfoPCHFACH-v5b0ext.c
	CellSelectReselectInfoSIB-11-12-ECN0.c
	CellSelectReselectInfoSIB-11-12-HCS-ECN0.c
	CellSelectReselectInfoSIB-11-12-HCS-RSCP.c
	CellSelectReselectInfoSIB-11-12-RSCP.c
	CellSelectReselectInfoSIB-11-12.c
	CellSelectReselectInfoSIB-3-4.c
	CellSelectReselectInfoTreselectionScaling-v5c0ext.c
	CellSynchronisationInfo.c
	CellToReport.c
	CellToReportList.c
	CellUpdate-v590ext.c
	CellUpdate-v690ext-IEs.c
	CellUpdate-v7xyext-IEs.c
	CellUpdate.c
	CellUpdateCause-ext.c
	CellUpdateCause.c
	CellUpdateConfirm-CCCH.c
	CellUpdateConfirm-r3-IEs.c
	CellUpdateConfirm-r4-IEs.c
	CellUpdateConfirm-r5-IEs.c
	CellUpdateConfirm-r6-IEs.c
	CellUpdateConfirm-r7-IEs.c
	CellUpdateConfirm-v3a0ext.c
	CellUpdateConfirm-v4b0ext-IEs.c
	CellUpdateConfirm-v590ext-IEs.c
	CellUpdateConfirm-v5d0ext-IEs.c
	CellUpdateConfirm-v690ext-IEs.c
	CellUpdateConfirm.c
	CellValueTag.c
	CellsForInterFreqMeasList.c
	CellsForInterRATMeasList.c
	CellsForIntraFreqMeasList.c
	Cfntargetsfnframeoffset.c
	ChannelAssignmentActive.c
	ChannelCodingType.c
	ChannelReqParamsForUCSM.c
	ChannelisationCode256.c
	ChipRateCapability-r7.c
	ChipRateCapability.c
	CipheringAlgorithm.c
	CipheringInfoPerRB-List-r4.c
	CipheringInfoPerRB-List-v3a0ext.c
	CipheringInfoPerRB-List.c
	CipheringInfoPerRB-r4.c
	CipheringInfoPerRB.c
	CipheringModeCommand.c
	CipheringModeInfo.c
	CipheringStatus.c
	CipheringStatusCNdomain-r4.c
	CipheringStatusCNdomain.c
	CipheringStatusList-r4.c
	CipheringStatusList.c
	ClosedLoopTimingAdjMode.c
	CodeChangeStatus.c
	CodeChangeStatusList.c
	CodeNumberDSCH.c
	CodePhaseSearchWindow.c
	CodeRange.c
	CodeWordSet.c
	CodingRate.c
	CommonDynamicTF-Info-DynamicTTI.c
	CommonDynamicTF-Info.c
	CommonDynamicTF-InfoList-DynamicTTI.c
	CommonDynamicTF-InfoList.c
	CommonTimeslotInfo.c
	CommonTimeslotInfoSCCPCH.c
	CommonTransChTFS-LCR.c
	CommonTransChTFS.c
	CompleteSIB-List.c
	CompleteSIB.c
	CompleteSIBshort.c
	CompressedModeMeasCapabFDD-ext.c
	CompressedModeMeasCapabFDD.c
	CompressedModeMeasCapabFDD2.c
	CompressedModeMeasCapabFDDList-ext.c
	CompressedModeMeasCapabFDDList.c
	CompressedModeMeasCapabFDDList2.c
	CompressedModeMeasCapabGSM.c
	CompressedModeMeasCapabGSMList.c
	CompressedModeMeasCapabMC.c
	CompressedModeMeasCapabTDD.c
	CompressedModeMeasCapabTDDList.c
	CompressedModeMeasCapability-LCR-r4.c
	CompressedModeMeasCapability-r4.c
	CompressedModeMeasCapability.c
	ConstantValue.c
	ConstantValueTdd.c
	CountC-SFN-Frame-difference.c
	CounterCheck-r3-IEs.c
	CounterCheck.c
	CounterCheckResponse.c
	DDI.c
	DGPS-CorrectionSatInfo.c
	DGPS-CorrectionSatInfoList.c
	DHS-Sync.c
	DL-AM-RLC-Mode-r5.c
	DL-AM-RLC-Mode.c
	DL-AddReconfTransChInfo2List.c
	DL-AddReconfTransChInfoList-r4.c
	DL-AddReconfTransChInfoList-r5.c
	DL-AddReconfTransChInfoList.c
	DL-AddReconfTransChInformation-r4.c
	DL-AddReconfTransChInformation-r5.c
	DL-AddReconfTransChInformation.c
	DL-AddReconfTransChInformation2.c
	DL-CCCH-Message.c
	DL-CCCH-MessageType.c
	DL-CCTrCh-r4.c
	DL-CCTrCh-r7.c
	DL-CCTrCh.c
	DL-CCTrChList-r4.c
	DL-CCTrChList-r7.c
	DL-CCTrChList.c
	DL-CCTrChListToRemove.c
	DL-CCTrChTPCList.c
	DL-CapabilityWithSimultaneousHS-DSCHConfig.c
	DL-ChannelisationCode.c
	DL-ChannelisationCodeList.c
	DL-CommonInformation-r4.c
	DL-CommonInformation-r5.c
	DL-CommonInformation-r6.c
	DL-CommonInformation-r7.c
	DL-CommonInformation.c
	DL-CommonInformationPost.c
	DL-CommonInformationPredef.c
	DL-CommonTransChInfo-r4.c
	DL-CommonTransChInfo.c
	DL-CompressedModeMethod.c
	DL-CounterSynchronisationInfo-r5.c
	DL-CounterSynchronisationInfo.c
	DL-DCCH-Message.c
	DL-DCCH-MessageType.c
	DL-DPCCH-BER.c
	DL-DPCH-InfoCommon-r4.c
	DL-DPCH-InfoCommon-r6.c
	DL-DPCH-InfoCommon.c
	DL-DPCH-InfoCommonPost.c
	DL-DPCH-InfoCommonPredef.c
	DL-DPCH-InfoPerRL-PostFDD.c
	DL-DPCH-InfoPerRL-PostTDD-LCR-r4.c
	DL-DPCH-InfoPerRL-PostTDD.c
	DL-DPCH-InfoPerRL-r4.c
	DL-DPCH-InfoPerRL-r5.c
	DL-DPCH-InfoPerRL-r6.c
	DL-DPCH-InfoPerRL-r7.c
	DL-DPCH-InfoPerRL.c
	DL-DPCH-PowerControlInfo.c
	DL-DeletedTransChInfoList-r5.c
	DL-DeletedTransChInfoList.c
	DL-FDPCH-InfoCommon-r6.c
	DL-FDPCH-InfoPerRL-r6.c
	DL-FrameType.c
	DL-HSPDSCH-Information-r6.c
	DL-HSPDSCH-Information-r7.c
	DL-HSPDSCH-Information.c
	DL-HSPDSCH-TS-Configuration-VHCR.c
	DL-HSPDSCH-TS-Configuration.c
	DL-InformationPerRL-List-r4.c
	DL-InformationPerRL-List-r5.c
	DL-InformationPerRL-List-r5bis.c
	DL-InformationPerRL-List-r6.c
	DL-InformationPerRL-List-r7.c
	DL-InformationPerRL-List.c
	DL-InformationPerRL-ListPostFDD.c
	DL-InformationPerRL-PostFDD.c
	DL-InformationPerRL-PostTDD-LCR-r4.c
	DL-InformationPerRL-PostTDD.c
	DL-InformationPerRL-r4.c
	DL-InformationPerRL-r5.c
	DL-InformationPerRL-r5bis.c
	DL-InformationPerRL-r6.c
	DL-InformationPerRL-r7.c
	DL-InformationPerRL.c
	DL-LogicalChannelMapping-r5.c
	DL-LogicalChannelMapping.c
	DL-LogicalChannelMappingList-r5.c
	DL-LogicalChannelMappingList.c
	DL-PDSCH-Information.c
	DL-PhysChCapabilityFDD-r4.c
	DL-PhysChCapabilityFDD-r5.c
	DL-PhysChCapabilityFDD-v380ext.c
	DL-PhysChCapabilityFDD.c
	DL-PhysChCapabilityTDD-768.c
	DL-PhysChCapabilityTDD-LCR-r4.c
	DL-PhysChCapabilityTDD-LCR-r5.c
	DL-PhysChCapabilityTDD-r5.c
	DL-PhysChCapabilityTDD.c
	DL-RFC3095-Context.c
	DL-RFC3095-r4.c
	DL-RLC-Mode-r5.c
	DL-RLC-Mode-r6.c
	DL-RLC-Mode.c
	DL-RLC-StatusInfo.c
	DL-Reception-Window-Size-r6.c
	DL-SHCCH-Message.c
	DL-SHCCH-MessageType.c
	DL-TM-RLC-Mode.c
	DL-TPC-PowerOffsetPerRL-List.c
	DL-TPC-PowerOffsetPerRL.c
	DL-TS-ChannelisationCode-VHCR.c
	DL-TS-ChannelisationCode.c
	DL-TS-ChannelisationCodesShort-VHCR.c
	DL-TS-ChannelisationCodesShort.c
	DL-TrCH-Type.c
	DL-TrCH-TypeId1-r5.c
	DL-TrCH-TypeId2-r5.c
	DL-TransChCapability.c
	DL-TransportChannelBLER.c
	DL-TransportChannelIdentity-r5.c
	DL-TransportChannelIdentity.c
	DL-TransportChannelType-r5.c
	DL-TransportChannelType.c
	DL-UM-RLC-LI-size.c
	DL-UM-RLC-Mode-r5.c
	DL-UM-RLC-Mode-r6.c
	DPC-Mode.c
	DPCCH-PowerOffset.c
	DPCCH-PowerOffset2.c
	DPCH-CompressedModeInfo.c
	DPCH-CompressedModeStatusInfo.c
	DPCH-FrameOffset.c
	DRAC-ClassIdentity.c
	DRAC-StaticInformation.c
	DRAC-StaticInformationList.c
	DRAC-SysInfo.c
	DRAC-SysInfoList.c
	DSCH-Mapping.c
	DSCH-MappingList.c
	DSCH-RNTI.c
	DSCH-RadioLinkIdentifier.c
	DSCH-TransportChannelsInfo-foo.c
	DSCH-TransportChannelsInfo.c
	DedicatedDynamicTF-Info-DynamicTTI.c
	DedicatedDynamicTF-Info.c
	DedicatedDynamicTF-InfoList-DynamicTTI.c
	DedicatedDynamicTF-InfoList.c
	DedicatedTransChTFS.c
	DefaultConfigIdentity-r4.c
	DefaultConfigIdentity-r5.c
	DefaultConfigIdentity-r6.c
	DefaultConfigIdentity.c
	DefaultConfigMode.c
	DefaultDPCH-OffsetValueFDD.c
	DefaultDPCH-OffsetValueTDD.c
	DelayRestrictionFlag.c
	DeltaACK.c
	DeltaCQI.c
	DeltaNACK.c
	DeltaPRC.c
	DeltaPp-m.c
	DeltaQrxlevmin.c
	DeltaRRC.c
	DeltaRSCP.c
	DeltaRSCPPerCell.c
	DeltaSIR.c
	DiffCorrectionStatus.c
	Digit.c
	Dl-rate-matching-restriction.c
	DomainSpecificAccessRestriction-v670ext.c
	DomainSpecificAccessRestrictionForSharedNetwork-v670ext.c
	DomainSpecificAccessRestrictionList-v670ext.c
	DomainSpecificAccessRestrictionParam-v670ext.c
	DopplerUncertainty.c
	DownlinkAdditionalTimeslots-LCR-r4.c
	DownlinkAdditionalTimeslots-VHCR.c
	DownlinkAdditionalTimeslots.c
	DownlinkDirectTransfer-r3-IEs.c
	DownlinkDirectTransfer.c
	DownlinkTimeslotsCodes-LCR-r4.c
	DownlinkTimeslotsCodes-VHCR.c
	DownlinkTimeslotsCodes.c
	DurationTimeInfo.c
	DynamicPersistenceLevel.c
	DynamicPersistenceLevelList.c
	DynamicPersistenceLevelTF-List.c
	DynamicTFInformationCCCH.c
	E-AGCH-ChannelisationCode.c
	E-AGCH-Information.c
	E-DCH-AddReconf-MAC-d-Flow.c
	E-DCH-AddReconf-MAC-d-FlowList.c
	E-DCH-MAC-d-FlowIdentity.c
	E-DCH-MAC-d-FlowMaxRetrans.c
	E-DCH-MAC-d-FlowMultiplexingList.c
	E-DCH-MAC-d-FlowPowerOffset.c
	E-DCH-MinimumSet-E-TFCI.c
	E-DCH-RL-InfoNewServingCell.c
	E-DCH-RL-InfoOtherCell.c
	E-DCH-ReconfigurationInfo.c
	E-DCH-TTI.c
	E-DPCCH-DPCCH-PowerOffset.c
	E-DPCCH-Info.c
	E-DPDCH-Info.c
	E-DPDCH-MaxChannelisationCodes.c
	E-DPDCH-PL-NonMax.c
	E-DPDCH-PeriodicyOfSchedInfo.c
	E-DPDCH-Reference-E-TFCI.c
	E-DPDCH-Reference-E-TFCIList.c
	E-DPDCH-SchedulingInfoConfiguration.c
	E-DPDCH-SchedulingTransmConfiguration.c
	E-HICH-ChannelisationCode.c
	E-HICH-Information.c
	E-HICH-RGCH-SignatureSequence.c
	E-RGCH-CombinationIndex.c
	E-RGCH-Information.c
	E-RNTI.c
	E-TFCI-TableIndex.c
	ESN-DS-41.c
	EXT-UL-TimingAdvance.c
	EllipsoidPoint.c
	EllipsoidPointAltitude.c
	EllipsoidPointAltitudeEllipsoide.c
	EllipsoidPointUncertCircle.c
	EllipsoidPointUncertEllipse.c
	EnvironmentCharacterisation.c
	EphemerisParameter.c
	EstablishmentCause.c
	Event1a-LCR-r4.c
	Event1a-r4.c
	Event1a.c
	Event1b-LCR-r4.c
	Event1b-r4.c
	Event1b.c
	Event1c.c
	Event1d.c
	Event1e-r6.c
	Event1e.c
	Event1f-r6.c
	Event1f.c
	Event1j-r6.c
	Event2a-r6.c
	Event2a.c
	Event2b-r6.c
	Event2b.c
	Event2c-r6.c
	Event2c.c
	Event2d-r6.c
	Event2d.c
	Event2e-r6.c
	Event2e.c
	Event2f-r6.c
	Event2f.c
	Event3a.c
	Event3b.c
	Event3c.c
	Event3d.c
	EventIDInterFreq.c
	EventIDInterRAT.c
	EventIDIntraFreq.c
	EventResults.c
	ExpectReordering.c
	ExpirationTimeFactor.c
	ExplicitDiscard.c
	ExplicitTFCS-Configuration.c
	ExtraDopplerInfo.c
	FACH-MeasurementOccasionInfo-LCR-r4-ext.c
	FACH-MeasurementOccasionInfo.c
	FACH-PCH-Information.c
	FACH-PCH-InformationList.c
	FDD-UMTS-Frequency-List.c
	FPACH-Info-r4.c
	FailureCauseWithProtErr.c
	FailureCauseWithProtErrTrId.c
	Feedback-cycle.c
	FilterCoefficient.c
	FineSFN-SFN.c
	FirstSegment.c
	FirstSegmentShort.c
	ForbiddenAffectCell-LCR-r4.c
	ForbiddenAffectCell-r4.c
	ForbiddenAffectCell.c
	ForbiddenAffectCellList-LCR-r4.c
	ForbiddenAffectCellList-r4.c
	ForbiddenAffectCellList.c
	FreqQualityEstimateQuantity-FDD.c
	FreqQualityEstimateQuantity-TDD.c
	Frequency-Band.c
	FrequencyInfo.c
	FrequencyInfoCDMA2000.c
	FrequencyInfoFDD.c
	FrequencyInfoTDD.c
	GERAN-SystemInfoBlock.c
	GERAN-SystemInformation.c
	GERANIu-MessageList.c
	GERANIu-RadioAccessCapability.c
	GPS-MeasurementParam.c
	GPS-MeasurementParamList.c
	GPS-TOW-1msec.c
	GPS-TOW-Assist.c
	GPS-TOW-AssistList.c
	GSM-BA-Range-List.c
	GSM-BA-Range.c
	GSM-CarrierRSSI.c
	GSM-Classmark2.c
	GSM-Classmark3.c
	GSM-MS-RadioAccessCapability.c
	GSM-MeasuredResults.c
	GSM-MeasuredResultsList.c
	GSM-Measurements.c
	GSM-MessageList.c
	GSM-TargetCellInfo.c
	GSM-TargetCellInfoList.c
	GainFactor.c
	GainFactorInformation.c
	GroupIdentityWithReleaseInformation.c
	GroupReleaseInformation.c
	Gsm-map-IDNNS.c
	GsmSecurityCapability.c
	H-RNTI.c
	HARQ-Info.c
	HARQ-Preamble-Mode.c
	HARQMemorySize.c
	HCS-CellReselectInformation-ECN0.c
	HCS-CellReselectInformation-RSCP.c
	HCS-NeighbouringCellInformation-ECN0.c
	HCS-NeighbouringCellInformation-RSCP.c
	HCS-PRIO.c
	HCS-ServingCellInformation.c
	HS-ChannelisationCode-LCR.c
	HS-PDSCH-Midamble-Configuration-TDD128.c
	HS-SCCH-Codes.c
	HS-SCCH-Info-r6.c
	HS-SCCH-Info-r7.c
	HS-SCCH-Info.c
	HS-SCCH-TDD128.c
	HS-SCCH-TDD384-r6.c
	HS-SCCH-TDD384.c
	HS-SCCH-TDD768.c
	HS-SICH-Configuration-TDD128.c
	HS-SICH-Configuration-TDD384.c
	HS-SICH-Configuration-TDD768.c
	HS-SICH-Power-Control-Info-TDD384.c
	HS-SICH-Power-Control-Info-TDD768.c
	HSDSCH-Info.c
	HSDSCH-physical-layer-category.c
	HandoverFromUTRANCommand-CDMA2000-r3-IEs.c
	HandoverFromUTRANCommand-CDMA2000.c
	HandoverFromUTRANCommand-GERANIu-r5-IEs.c
	HandoverFromUTRANCommand-GERANIu.c
	HandoverFromUTRANCommand-GSM-r3-IEs.c
	HandoverFromUTRANCommand-GSM-r6-IEs.c
	HandoverFromUTRANCommand-GSM-v690ext-IEs.c
	HandoverFromUTRANCommand-GSM.c
	HandoverFromUTRANFailure.c
	HandoverFromUtranFailure-v590ext-IEs.c
	HandoverToUTRANCommand-r3-IEs.c
	HandoverToUTRANCommand-r4-IEs.c
	HandoverToUTRANCommand-r5-IEs.c
	HandoverToUTRANCommand-r6-IEs.c
	HandoverToUTRANCommand-r7-IEs.c
	HandoverToUTRANCommand.c
	HandoverToUTRANComplete.c
	HappyBit-DelayCondition.c
	HeaderCompressionInfo-r4.c
	HeaderCompressionInfo.c
	HeaderCompressionInfoList-r4.c
	HeaderCompressionInfoList.c
	HorizontalVelocity.c
	HorizontalVelocityWithUncertainty.c
	HorizontalWithVerticalVelocity.c
	HorizontalWithVerticalVelocityAndUncertainty.c
	Hysteresis.c
	HysteresisInterFreq.c
	IMEI-Digit.c
	IMEI.c
	IMSI-DS-41.c
	IMSI-GSM-MAP.c
	IMSI-and-ESN-DS-41.c
	IODE.c
	IP-Length.c
	IP-PCCPCH-r4.c
	IP-Spacing-TDD.c
	IP-Spacing.c
	IS-2000SpecificMeasInfo.c
	ITP.c
	IdentificationOfReceivedMessage.c
	ImplementationSpecificParams.c
	IndividualDL-CCTrCH-Info.c
	IndividualDL-CCTrCH-InfoList.c
	IndividualTS-Interference.c
	IndividualTS-InterferenceList.c
	IndividualTimeslotInfo-LCR-r4-ext.c
	IndividualTimeslotInfo-LCR-r4.c
	IndividualTimeslotInfo-VHCR.c
	IndividualTimeslotInfo.c
	IndividualUL-CCTrCH-Info.c
	IndividualUL-CCTrCH-InfoList.c
	InitialDirectTransfer-v3a0ext.c
	InitialDirectTransfer-v590ext.c
	InitialDirectTransfer-v690ext-IEs.c
	InitialDirectTransfer.c
	InitialPriorityDelayList.c
	InitialUE-Identity.c
	IntegrityCheckInfo.c
	IntegrityProtActivationInfo.c
	IntegrityProtInitNumber.c
	IntegrityProtectionAlgorithm.c
	IntegrityProtectionModeCommand.c
	IntegrityProtectionModeInfo.c
	IntegrityProtectionStatus.c
	Inter-FreqEventCriteria-v590ext.c
	Inter-FreqEventCriteriaList-v590ext.c
	InterFreqCell-LCR-r4.c
	InterFreqCell.c
	InterFreqCellID.c
	InterFreqCellInfoList-r4.c
	InterFreqCellInfoList.c
	InterFreqCellInfoSI-List-ECN0-LCR.c
	InterFreqCellInfoSI-List-ECN0.c
	InterFreqCellInfoSI-List-HCS-ECN0-LCR.c
	InterFreqCellInfoSI-List-HCS-ECN0.c
	InterFreqCellInfoSI-List-HCS-RSCP-LCR.c
	InterFreqCellInfoSI-List-HCS-RSCP.c
	InterFreqCellInfoSI-List-RSCP-LCR.c
	InterFreqCellInfoSI-List-RSCP.c
	InterFreqCellList-LCR-r4-ext.c
	InterFreqCellList.c
	InterFreqCellMeasuredResultsList.c
	InterFreqEvent-r6.c
	InterFreqEvent.c
	InterFreqEventList-r6.c
	InterFreqEventList.c
	InterFreqEventResults-LCR-r4-ext.c
	InterFreqEventResults.c
	InterFreqMeasQuantity.c
	InterFreqMeasuredResults.c
	InterFreqMeasuredResultsList.c
	InterFreqMeasurementSysInfo-ECN0-LCR-r4.c
	InterFreqMeasurementSysInfo-ECN0.c
	InterFreqMeasurementSysInfo-HCS-ECN0-LCR-r4.c
	InterFreqMeasurementSysInfo-HCS-ECN0.c
	InterFreqMeasurementSysInfo-HCS-RSCP-LCR-r4.c
	InterFreqMeasurementSysInfo-HCS-RSCP.c
	InterFreqMeasurementSysInfo-RSCP-LCR-r4.c
	InterFreqMeasurementSysInfo-RSCP.c
	InterFreqRACHRepCellsList.c
	InterFreqRACHReportingInfo.c
	InterFreqRepQuantityRACH-FDD.c
	InterFreqRepQuantityRACH-TDD.c
	InterFreqRepQuantityRACH-TDDList.c
	InterFreqReportCriteria-r4.c
	InterFreqReportCriteria-r6.c
	InterFreqReportCriteria.c
	InterFreqReportingCriteria-r6.c
	InterFreqReportingCriteria.c
	InterFreqReportingQuantity.c
	InterFrequencyMeasuredResultsList-v590ext.c
	InterFrequencyMeasurement-r4.c
	InterFrequencyMeasurement-r6.c
	InterFrequencyMeasurement.c
	InterRAT-ChangeFailureCause.c
	InterRAT-HO-FailureCause.c
	InterRAT-TargetCellDescription.c
	InterRAT-UE-RadioAccessCapability-v590ext.c
	InterRAT-UE-RadioAccessCapability-v690ext.c
	InterRAT-UE-RadioAccessCapability.c
	InterRAT-UE-RadioAccessCapabilityList-r5.c
	InterRAT-UE-RadioAccessCapabilityList.c
	InterRAT-UE-SecurityCapList.c
	InterRAT-UE-SecurityCapability.c
	InterRATCellID.c
	InterRATCellIndividualOffset.c
	InterRATCellInfoIndication.c
	InterRATCellInfoList-B.c
	InterRATCellInfoList-r4.c
	InterRATCellInfoList-r6.c
	InterRATCellInfoList.c
	InterRATEvent.c
	InterRATEventList.c
	InterRATEventResults.c
	InterRATHandoverInfo-r3-add-ext-IEs.c
	InterRATHandoverInfo-v390ext-IEs.c
	InterRATHandoverInfo-v3a0ext-IEs.c
	InterRATHandoverInfo-v3d0ext-IEs.c
	InterRATHandoverInfo-v3g0ext-IEs.c
	InterRATHandoverInfo-v4b0ext-IEs.c
	InterRATHandoverInfo-v4d0ext-IEs.c
	InterRATHandoverInfo-v590ext-IEs.c
	InterRATHandoverInfo-v690ext-IEs.c
	InterRATHandoverInfo-v690ext1-IEs.c
	InterRATHandoverInfo-v7xyext-IEs.c
	InterRATHandoverInfo.c
	InterRATHandoverInfoWithInterRATCapabilities-r3-IEs.c
	InterRATHandoverInfoWithInterRATCapabilities-r3.c
	InterRATHandoverInfoWithInterRATCapabilities-v390ext-IEs.c
	InterRATHandoverInfoWithInterRATCapabilities-v690ext-IEs.c
	InterRATInfo-r6.c
	InterRATInfo.c
	InterRATMeasQuantity.c
	InterRATMeasuredResults.c
	InterRATMeasuredResultsList.c
	InterRATMeasurement-r4.c
	InterRATMeasurement-r6.c
	InterRATMeasurement.c
	InterRATMeasurementSysInfo-B.c
	InterRATMeasurementSysInfo.c
	InterRATReportCriteria.c
	InterRATReportingCriteria.c
	InterRATReportingQuantity.c
	Intra-FreqEventCriteriaList-v590ext.c
	IntraDomainNasNodeSelector.c
	IntraFreqCellID.c
	IntraFreqCellInfoList-r4.c
	IntraFreqCellInfoList.c
	IntraFreqCellInfoSI-List-ECN0-LCR-r4.c
	IntraFreqCellInfoSI-List-ECN0.c
	IntraFreqCellInfoSI-List-HCS-ECN0-LCR-r4.c
	IntraFreqCellInfoSI-List-HCS-ECN0.c
	IntraFreqCellInfoSI-List-HCS-RSCP-LCR-r4.c
	IntraFreqCellInfoSI-List-HCS-RSCP.c
	IntraFreqCellInfoSI-List-RSCP-LCR-r4.c
	IntraFreqCellInfoSI-List-RSCP.c
	IntraFreqEvent-1d-r5.c
	IntraFreqEvent-LCR-r4.c
	IntraFreqEvent-r4.c
	IntraFreqEvent-r6.c
	IntraFreqEvent.c
	IntraFreqEventCriteria-LCR-r4.c
	IntraFreqEventCriteria-r4.c
	IntraFreqEventCriteria-r6.c
	IntraFreqEventCriteria.c
	IntraFreqEventCriteriaList-LCR-r4.c
	IntraFreqEventCriteriaList-r4.c
	IntraFreqEventCriteriaList-r6.c
	IntraFreqEventCriteriaList.c
	IntraFreqEventResults.c
	IntraFreqMeasQuantity-FDD.c
	IntraFreqMeasQuantity-TDD.c
	IntraFreqMeasQuantity-TDDList.c
	IntraFreqMeasQuantity.c
	IntraFreqMeasuredResultsList.c
	IntraFreqMeasurementSysInfo-ECN0-LCR-r4.c
	IntraFreqMeasurementSysInfo-ECN0.c
	IntraFreqMeasurementSysInfo-HCS-ECN0-LCR-r4.c
	IntraFreqMeasurementSysInfo-HCS-ECN0.c
	IntraFreqMeasurementSysInfo-HCS-RSCP-LCR-r4.c
	IntraFreqMeasurementSysInfo-HCS-RSCP.c
	IntraFreqMeasurementSysInfo-RSCP-LCR-r4.c
	IntraFreqMeasurementSysInfo-RSCP.c
	IntraFreqRepQuantityRACH-FDD.c
	IntraFreqRepQuantityRACH-TDD.c
	IntraFreqRepQuantityRACH-TDDList.c
	IntraFreqReportCriteria-r4.c
	IntraFreqReportCriteria-r6.c
	IntraFreqReportCriteria.c
	IntraFreqReportingCriteria-1b-r5.c
	IntraFreqReportingCriteria-LCR-r4.c
	IntraFreqReportingCriteria-r4.c
	IntraFreqReportingCriteria-r6-ext.c
	IntraFreqReportingCriteria-r6.c
	IntraFreqReportingCriteria.c
	IntraFreqReportingQuantity.c
	IntraFreqReportingQuantityForRACH.c
	IntraFrequencyMeasuredResultsList-v590ext.c
	IntraFrequencyMeasurement-r4.c
	IntraFrequencyMeasurement-r6.c
	IntraFrequencyMeasurement.c
	LAI.c
	LastSegment.c
	LastSegmentShort.c
	LogicalChannelByRB.c
	LogicalChannelIdentity.c
	LogicalChannelList.c
	LosslessSRNS-RelocSupport.c
	MAC-LogicalChannelPriority.c
	MAC-d-FlowIdentity.c
	MAC-d-FlowIdentityDCHandHSDSCH.c
	MAC-d-HFN-initial-value.c
	MAC-d-PDU-SizeInfo-List.c
	MAC-d-PDUsizeInfo.c
	MAC-hs-AddReconfQueue-List.c
	MAC-hs-AddReconfQueue.c
	MAC-hs-DelQueue-List.c
	MAC-hs-DelQueue.c
	MAC-hs-WindowSize.c
	MBMS-AccessProbabilityFactor.c
	MBMS-CellGroupIdentity-r6.c
	MBMS-CommonCCTrChIdentity.c
	MBMS-CommonPhyChIdentity.c
	MBMS-CommonRBIdentity.c
	MBMS-CommonRBInformation-r6.c
	MBMS-CommonRBInformationList-r6.c
	MBMS-CommonTrChIdentity.c
	MBMS-ConnectedModeCountingScope.c
	MBMS-CurrentCell-SCCPCH-r6.c
	MBMS-CurrentCell-SCCPCHList-r6.c
	MBMS-FACHCarryingMTCH-List.c
	MBMS-JoinedInformation-r6.c
	MBMS-L1CombiningSchedule-1024.c
	MBMS-L1CombiningSchedule-128.c
	MBMS-L1CombiningSchedule-256.c
	MBMS-L1CombiningSchedule-32.c
	MBMS-L1CombiningSchedule-512.c
	MBMS-L1CombiningSchedule-64.c
	MBMS-L1CombiningSchedule.c
	MBMS-L1CombiningTransmTimeDiff.c
	MBMS-L23Configuration.c
	MBMS-LogicalChIdentity.c
	MBMS-MCCH-ConfigurationInfo-r6.c
	MBMS-MICHConfigurationInfo-r6.c
	MBMS-MICHConfigurationInfo-r7.c
	MBMS-MICHNotificationIndLength.c
	MBMS-MICHPowerOffset.c
	MBMS-MSCH-ConfigurationInfo-r6.c
	MBMS-MSCHSchedulingInfo.c
	MBMS-ModifedService-r6.c
	MBMS-ModifedServiceList-r6.c
	MBMS-NI-CountPerFrame.c
	MBMS-NeighbouringCellSCCPCH-r6.c
	MBMS-NeighbouringCellSCCPCHList-r6.c
	MBMS-NumberOfNeighbourCells-r6.c
	MBMS-PFLIndex.c
	MBMS-PFLInfo.c
	MBMS-PL-ServiceRestrictInfo-r6.c
	MBMS-PTM-RBInformation-C.c
	MBMS-PTM-RBInformation-CList.c
	MBMS-PTM-RBInformation-N.c
	MBMS-PTM-RBInformation-NList.c
	MBMS-PTMActivationTime-r6.c
	MBMS-PhyChInformation-r6.c
	MBMS-PhyChInformationList-r6.c
	MBMS-PreferredFreqRequest-r6.c
	MBMS-PreferredFrequencyInfo-r6.c
	MBMS-PreferredFrequencyList-r6.c
	MBMS-Qoffset.c
	MBMS-RequiredUEAction-Mod.c
	MBMS-RequiredUEAction-UMod.c
	MBMS-SCCPCHIdentity.c
	MBMS-SCCPCHPwrOffsetDiff.c
	MBMS-SIBType5-SCCPCH-r6.c
	MBMS-SIBType5-SCCPCHList-r6.c
	MBMS-ServiceAccessInfo-r6.c
	MBMS-ServiceAccessInfoList-r6.c
	MBMS-ServiceIdentity-r6.c
	MBMS-ServiceSchedulingInfo-r6.c
	MBMS-ServiceSchedulingInfoList-r6.c
	MBMS-ServiceTransmInfo.c
	MBMS-ServiceTransmInfoList.c
	MBMS-SessionIdentity.c
	MBMS-ShortTransmissionID.c
	MBMS-SoftComb-TimingOffset.c
	MBMS-TCTF-Presence.c
	MBMS-TimersAndCounters-r6.c
	MBMS-TrCHInformation-Curr.c
	MBMS-TrCHInformation-CurrList.c
	MBMS-TrCHInformation-Neighb.c
	MBMS-TrCHInformation-NeighbList.c
	MBMS-TrCHInformation-SIB5.c
	MBMS-TrCHInformation-SIB5List.c
	MBMS-TransmissionIdentity.c
	MBMS-TranspChInfoForCCTrCh-r6.c
	MBMS-TranspChInfoForEachCCTrCh-r6.c
	MBMS-TranspChInfoForEachTrCh-r6.c
	MBMS-TranspChInfoForTrCh-r6.c
	MBMS-UnmodifiedService-r6.c
	MBMS-UnmodifiedServiceList-r6.c
	MBMSAccessInformation.c
	MBMSCommonPTMRBInformation.c
	MBMSCurrentCellPTMRBInformation.c
	MBMSGeneralInformation-v7xyext-IEs.c
	MBMSGeneralInformation.c
	MBMSModificationRequest.c
	MBMSModifiedServicesInformation.c
	MBMSNeighbouringCellPTMRBInformation.c
	MBMSSchedulingInformation.c
	MBMSUnmodifiedServicesInformation.c
	MCC.c
	MCCH-Message.c
	MCCH-MessageType.c
	MIB-ValueTag.c
	MNC.c
	MSCH-Message.c
	MSCH-MessageType.c
	MapParameter.c
	Mapping-LCR-r4.c
	Mapping.c
	MappingFunctionParameter.c
	MappingFunctionParameterList.c
	MappingFunctionType.c
	MappingInfo.c
	MasterInformationBlock-v690ext.c
	MasterInformationBlock.c
	MaxAllowedUL-TX-Power.c
	MaxAvailablePCPCH-Number.c
	MaxDAT-Retransmissions.c
	MaxDAT.c
	MaxHcContextSpace-r5-ext.c
	MaxHcContextSpace-r5.c
	MaxHcContextSpace.c
	MaxMRW.c
	MaxNoBits.c
	MaxNoDPDCH-BitsTransmitted.c
	MaxNoPhysChBitsReceived.c
	MaxNoSCCPCH-RL.c
	MaxNumberOfReportingCellsType1.c
	MaxNumberOfReportingCellsType2.c
	MaxNumberOfReportingCellsType3.c
	MaxNumberOfTF.c
	MaxNumberOfTFC-DL.c
	MaxNumberOfTFC-UL.c
	MaxPDCP-SN-WindowSize.c
	MaxPhysChPerFrame-768.c
	MaxPhysChPerFrame.c
	MaxPhysChPerSubFrame-r4.c
	MaxPhysChPerTS-768.c
	MaxPhysChPerTS.c
	MaxPhysChPerTimeslot.c
	MaxPowerIncrease-r4.c
	MaxROHC-ContextSessions-r4.c
	MaxRST.c
	MaxReportedCellsOnRACH.c
	MaxReportedCellsOnRACHinterFreq.c
	MaxSimultaneousCCTrCH-Count.c
	MaxSimultaneousTransChsDL.c
	MaxSimultaneousTransChsUL.c
	MaxTFCI-Field2Value.c
	MaxTS-PerFrame.c
	MaxTS-PerSubFrame-r4.c
	MaxTransportBlocksDL.c
	MaxTransportBlocksUL.c
	MaximumAM-EntityNumberRLC-Cap.c
	MaximumBitRate.c
	MaximumRLC-WindowSize.c
	MeasuredResults-LCR-r4.c
	MeasuredResults-v390ext.c
	MeasuredResults-v590ext.c
	MeasuredResults-v7xyext.c
	MeasuredResults.c
	MeasuredResultsList-LCR-r4-ext.c
	MeasuredResultsList.c
	MeasuredResultsOnRACH.c
	MeasuredResultsOnRACHinterFreq.c
	Measurement-Feedback-Info.c
	MeasurementCapability-r4-ext.c
	MeasurementCapability-r4.c
	MeasurementCapability.c
	MeasurementCapabilityExt.c
	MeasurementCapabilityExt2.c
	MeasurementCommand-r4.c
	MeasurementCommand-r6.c
	MeasurementCommand.c
	MeasurementCommandWithType-r4.c
	MeasurementCommandWithType-r6.c
	MeasurementCommandWithType.c
	MeasurementControl-r3-IEs.c
	MeasurementControl-r4-IEs.c
	MeasurementControl-r6-IEs.c
	MeasurementControl-v390ext.c
	MeasurementControl-v3a0ext.c
	MeasurementControl-v590ext-IEs.c
	MeasurementControl-v5b0ext-IEs.c
	MeasurementControl-v6a0ext-IEs.c
	MeasurementControl-v7xyext-IEs.c
	MeasurementControl.c
	MeasurementControlFailure-v590ext-IEs.c
	MeasurementControlFailure.c
	MeasurementControlSysInfo-LCR-r4-ext.c
	MeasurementControlSysInfo.c
	MeasurementIdentity.c
	MeasurementPowerOffset.c
	MeasurementQuantityGSM.c
	MeasurementReport-v390ext.c
	MeasurementReport-v4b0ext-IEs.c
	MeasurementReport-v590ext-IEs.c
	MeasurementReport-v5b0ext-IEs.c
	MeasurementReport-v690ext-IEs.c
	MeasurementReport-v7xyext-IEs.c
	MeasurementReport.c
	MeasurementReportingMode.c
	MeasurementType-r4.c
	MeasurementType-r6.c
	MeasurementType.c
	MeasurementValidity.c
	MessType.c
	MessageAuthenticationCode.c
	MidambleConfigurationBurstType1and3.c
	MidambleConfigurationBurstType2-VHCR.c
	MidambleConfigurationBurstType2.c
	MidambleShiftAndBurstType-DL-VHCR.c
	MidambleShiftAndBurstType-DL.c
	MidambleShiftAndBurstType-LCR-r4.c
	MidambleShiftAndBurstType-VHCR.c
	MidambleShiftAndBurstType.c
	MidambleShiftLong.c
	MidambleShiftShort-VHCR.c
	MidambleShiftShort.c
	Min-P-REV.c
	MinimumSF-DL-768.c
	MinimumSF-DL.c
	MinimumSF-UL.c
	MinimumSpreadingFactor.c
	MonitoredCellRACH-List.c
	MonitoredCellRACH-Result.c
	MultiCodeInfo.c
	MultiModeCapability.c
	MultiModeRAT-Capability-v590ext.c
	MultiModeRAT-Capability-v680ext.c
	MultiRAT-Capability.c
	MultipathIndicator.c
	MultiplePLMN-List-r6.c
	N-300.c
	N-301.c
	N-302.c
	N-304.c
	N-308.c
	N-310.c
	N-312-r5.c
	N-312.c
	N-312ext.c
	N-313.c
	N-315-r5.c
	N-315.c
	N-315ext.c
	N-AP-RetransMax.c
	N-AccessFails.c
	N-CR-T-CRMaxHyst.c
	N-EOT.c
	N-GAP.c
	N-PCH.c
	N-StartMessage.c
	NAS-Message.c
	NAS-Synchronisation-Indicator.c
	NAS-SystemInformationANSI-41.c
	NAS-SystemInformationGSM-MAP.c
	NB01.c
	NC-Mode.c
	NCC.c
	NF-BO-AllBusy.c
	NF-BO-Mismatch.c
	NF-BO-NoAICH.c
	NF-Max.c
	NID.c
	NS-BO-Busy.c
	NS-IP.c
	NavigationModelSatInfo.c
	NavigationModelSatInfoList.c
	Neighbour-v390ext.c
	Neighbour.c
	NeighbourList-v390ext.c
	NeighbourList.c
	NeighbourQuality.c
	NetworkAssistedGPS-Supported.c
	NewInterFreqCell-r4.c
	NewInterFreqCell.c
	NewInterFreqCellList-r4.c
	NewInterFreqCellList.c
	NewInterFreqCellSI-ECN0-LCR-r4.c
	NewInterFreqCellSI-ECN0.c
	NewInterFreqCellSI-HCS-ECN0-LCR-r4.c
	NewInterFreqCellSI-HCS-ECN0.c
	NewInterFreqCellSI-HCS-RSCP-LCR-r4.c
	NewInterFreqCellSI-HCS-RSCP.c
	NewInterFreqCellSI-List-ECN0-LCR-r4.c
	NewInterFreqCellSI-List-ECN0.c
	NewInterFreqCellSI-List-HCS-ECN0-LCR-r4.c
	NewInterFreqCellSI-List-HCS-ECN0.c
	NewInterFreqCellSI-List-HCS-RSCP-LCR-r4.c
	NewInterFreqCellSI-List-HCS-RSCP.c
	NewInterFreqCellSI-List-RSCP-LCR-r4.c
	NewInterFreqCellSI-List-RSCP.c
	NewInterFreqCellSI-RSCP-LCR-r4.c
	NewInterFreqCellSI-RSCP.c
	NewInterRATCell-B.c
	NewInterRATCell.c
	NewInterRATCellList-B.c
	NewInterRATCellList.c
	NewIntraFreqCell-r4.c
	NewIntraFreqCell.c
	NewIntraFreqCellList-r4.c
	NewIntraFreqCellList.c
	NewIntraFreqCellSI-ECN0-LCR-r4.c
	NewIntraFreqCellSI-ECN0.c
	NewIntraFreqCellSI-HCS-ECN0-LCR-r4.c
	NewIntraFreqCellSI-HCS-ECN0.c
	NewIntraFreqCellSI-HCS-RSCP-LCR-r4.c
	NewIntraFreqCellSI-HCS-RSCP.c
	NewIntraFreqCellSI-List-ECN0-LCR-r4.c
	NewIntraFreqCellSI-List-ECN0.c
	NewIntraFreqCellSI-List-HCS-ECN0-LCR-r4.c
	NewIntraFreqCellSI-List-HCS-ECN0.c
	NewIntraFreqCellSI-List-HCS-RSCP-LCR-r4.c
	NewIntraFreqCellSI-List-HCS-RSCP.c
	NewIntraFreqCellSI-List-RSCP-LCR-r4.c
	NewIntraFreqCellSI-List-RSCP.c
	NewIntraFreqCellSI-RSCP-LCR-r4.c
	NewIntraFreqCellSI-RSCP.c
	NidentifyAbort.c
	NoExplicitDiscard.c
	Non-allowedTFC-List.c
	NonUsedFreqParameter-r6.c
	NonUsedFreqParameter.c
	NonUsedFreqParameterList-r6.c
	NonUsedFreqParameterList.c
	NonUsedFreqWList-r6.c
	NumberOfDPDCH.c
	NumberOfFBI-Bits.c
	NumberOfTbSizeAndTTIList-foo.c
	NumberOfTbSizeAndTTIList.c
	NumberOfTransportBlocks.c
	OTDOA-SearchWindowSize.c
	ObservedTimeDifferenceToGSM.c
	OctetModeRLC-SizeInfoType1.c
	OctetModeRLC-SizeInfoType2.c
	OngoingMeasRep-r4.c
	OngoingMeasRep-r5.c
	OngoingMeasRep-r6.c
	OngoingMeasRep.c
	OngoingMeasRepList-r4.c
	OngoingMeasRepList-r5.c
	OngoingMeasRepList-r6.c
	OngoingMeasRepList.c
	OpenLoopPowerControl-IPDL-TDD-r4.c
	OpenLoopPowerControl-TDD.c
	P-REV.c
	P-TMSI-GSM-MAP.c
	P-TMSI-and-RAI-GSM-MAP.c
	PC-Preamble.c
	PCCH-Message.c
	PCCH-MessageType.c
	PCP-Length.c
	PCPCH-ChannelInfo.c
	PCPCH-ChannelInfoList.c
	PCPICH-UsageForChannelEst.c
	PDCP-Capability-r4-ext.c
	PDCP-Capability-r4.c
	PDCP-Capability-r5-ext.c
	PDCP-Capability-r5-ext2.c
	PDCP-Capability-r5.c
	PDCP-Capability-r6.c
	PDCP-Capability.c
	PDCP-Info-r4.c
	PDCP-Info.c
	PDCP-InfoReconfig-r4.c
	PDCP-InfoReconfig.c
	PDCP-PDU-Header.c
	PDCP-ROHC-TargetMode.c
	PDCP-SN-Info.c
	PDSCH-CapacityAllocationInfo-r4.c
	PDSCH-CapacityAllocationInfo-r7.c
	PDSCH-CapacityAllocationInfo.c
	PDSCH-CodeInfo.c
	PDSCH-CodeInfoList.c
	PDSCH-CodeMap.c
	PDSCH-CodeMapList.c
	PDSCH-CodeMapping.c
	PDSCH-Identity.c
	PDSCH-Info-LCR-r4.c
	PDSCH-Info-r4.c
	PDSCH-Info-r7.c
	PDSCH-Info.c
	PDSCH-PowerControlInfo.c
	PDSCH-SHO-DCH-Info.c
	PDSCH-SysInfo-HCR-r5.c
	PDSCH-SysInfo-LCR-r4.c
	PDSCH-SysInfo-r7.c
	PDSCH-SysInfo.c
	PDSCH-SysInfoList-HCR-r5.c
	PDSCH-SysInfoList-LCR-r4.c
	PDSCH-SysInfoList-SFN-HCR-r5-foo.c
	PDSCH-SysInfoList-SFN-HCR-r5.c
	PDSCH-SysInfoList-SFN-LCR-r4-foo.c
	PDSCH-SysInfoList-SFN-LCR-r4.c
	PDSCH-SysInfoList-SFN-foo.c
	PDSCH-SysInfoList-SFN.c
	PDSCH-SysInfoList-r7.c
	PDSCH-SysInfoList.c
	PI-CountPerFrame.c
	PICH-Info-LCR-r4.c
	PICH-Info-r7.c
	PICH-Info.c
	PICH-PowerOffset.c
	PLCCH-Info.c
	PLMN-Identity.c
	PLMN-IdentityWithOptionalMCC-r6.c
	PLMN-Type.c
	PLMN-ValueTag.c
	PLMNIdentitiesOfNeighbourCells.c
	PLMNsOfInterFreqCellsList.c
	PLMNsOfInterRATCellsList.c
	PLMNsOfIntraFreqCellsList.c
	PLMNsOfXXXCellsList-foo.c
	PNBSCH-Allocation-r4.c
	PRACH-ChanCodes-LCR-r4.c
	PRACH-Definition-LCR-r4.c
	PRACH-Midamble.c
	PRACH-Partitioning-LCR-r4.c
	PRACH-Partitioning-r7.c
	PRACH-Partitioning.c
	PRACH-PowerOffset.c
	PRACH-RACH-Info-LCR-r4.c
	PRACH-RACH-Info-r7.c
	PRACH-RACH-Info.c
	PRACH-SystemInformation-LCR-r4.c
	PRACH-SystemInformation-r7.c
	PRACH-SystemInformation.c
	PRACH-SystemInformationList-LCR-r4.c
	PRACH-SystemInformationList-r7.c
	PRACH-SystemInformationList.c
	PRC.c
	PUSCH-CapacityAllocationInfo-r4.c
	PUSCH-CapacityAllocationInfo-r7.c
	PUSCH-CapacityAllocationInfo.c
	PUSCH-Identity.c
	PUSCH-Info-LCR-r4.c
	PUSCH-Info-VHCR.c
	PUSCH-Info-r4.c
	PUSCH-Info.c
	PUSCH-PowerControlInfo-r4.c
	PUSCH-PowerControlInfo-r7.c
	PUSCH-SysInfo-HCR-r5.c
	PUSCH-SysInfo-LCR-r4.c
	PUSCH-SysInfo-VHCR.c
	PUSCH-SysInfo.c
	PUSCH-SysInfoList-HCR-r5.c
	PUSCH-SysInfoList-LCR-r4.c
	PUSCH-SysInfoList-SFN-HCR-r5-foo.c
	PUSCH-SysInfoList-SFN-HCR-r5.c
	PUSCH-SysInfoList-SFN-LCR-r4-foo.c
	PUSCH-SysInfoList-SFN-LCR-r4.c
	PUSCH-SysInfoList-SFN-VHCR-foo.c
	PUSCH-SysInfoList-SFN-VHCR.c
	PUSCH-SysInfoList-SFN-foo.c
	PUSCH-SysInfoList-SFN.c
	PUSCH-SysInfoList.c
	PUSCHCapacityRequest-v590ext.c
	PUSCHCapacityRequest.c
	PagingCause.c
	PagingIndicatorLength.c
	PagingRecord.c
	PagingRecord2-r5.c
	PagingRecord2List-r5.c
	PagingRecordList.c
	PagingRecordTypeID.c
	PagingType1-v590ext-IEs.c
	PagingType1.c
	PagingType2.c
	Pathloss.c
	PenaltyTime-ECN0.c
	PenaltyTime-RSCP.c
	PendingTimeAfterTrigger.c
	PeriodicReportingInfo-1b.c
	PeriodicalOrEventTrigger.c
	PeriodicalReportingCriteria.c
	PeriodicalWithReportingCellStatus.c
	PersistenceScalingFactor.c
	PersistenceScalingFactorList.c
	PhysicalChannelCapability-LCR-r4.c
	PhysicalChannelCapability-edch-r6.c
	PhysicalChannelCapability-hspdsch-r5.c
	PhysicalChannelCapability-r4.c
	PhysicalChannelCapability-r5.c
	PhysicalChannelCapability-r7.c
	PhysicalChannelCapability.c
	PhysicalChannelReconfiguration-r3-IEs.c
	PhysicalChannelReconfiguration-r4-IEs.c
	PhysicalChannelReconfiguration-r5-IEs.c
	PhysicalChannelReconfiguration-r6-IEs.c
	PhysicalChannelReconfiguration-r7-IEs.c
	PhysicalChannelReconfiguration-v3a0ext.c
	PhysicalChannelReconfiguration-v4b0ext-IEs.c
	PhysicalChannelReconfiguration-v590ext-IEs.c
	PhysicalChannelReconfiguration-v690ext-IEs.c
	PhysicalChannelReconfiguration.c
	PhysicalChannelReconfigurationComplete-v7xyext-IEs.c
	PhysicalChannelReconfigurationComplete.c
	PhysicalChannelReconfigurationFailure.c
	PhysicalSharedChannelAllocation-r3-IEs.c
	PhysicalSharedChannelAllocation-r4-IEs.c
	PhysicalSharedChannelAllocation-v690ext-IEs.c
	PhysicalSharedChannelAllocation-v7xyext-IEs.c
	PhysicalSharedChannelAllocation.c
	PichChannelisationCodeList-LCR-r4.c
	PilotBits128.c
	PilotBits256.c
	Poll-PDU.c
	Poll-SDU.c
	PollWindow.c
	PollingInfo.c
	PositionEstimate.c
	PositionFixedOrFlexible.c
	PositioningMethod.c
	PowerControlAlgorithm.c
	PowerOffsetInfoShort.c
	PowerOffsetInformation.c
	PowerOffsetPilot-pdpdch.c
	PowerOffsetPp-m.c
	PowerOffsetTPC-pdpdch.c
	PowerRampStep.c
	PreDefPhyChConfiguration.c
	PreDefRadioConfiguration.c
	PreDefTransChConfiguration.c
	PreambleRetransMax.c
	PreambleScramblingCodeWordNumber.c
	PredefinedConfigIdentity.c
	PredefinedConfigIdentityAndValueTag.c
	PredefinedConfigSetWithDifferentValueTag.c
	PredefinedConfigSetsWithDifferentValueTag.c
	PredefinedConfigStatusInfo.c
	PredefinedConfigStatusList.c
	PredefinedConfigStatusListComp.c
	PredefinedConfigStatusListVarSz.c
	PredefinedConfigValueTag.c
	PredefinedConfigValueTagList.c
	PredefinedRB-Configuration.c
	PrimaryCCPCH-Info-LCR-r4-ext.c
	PrimaryCCPCH-Info-LCR-r4.c
	PrimaryCCPCH-Info-r4.c
	PrimaryCCPCH-Info-r7.c
	PrimaryCCPCH-Info.c
	PrimaryCCPCH-InfoPost.c
	PrimaryCCPCH-InfoPostTDD-LCR-r4.c
	PrimaryCCPCH-RSCP.c
	PrimaryCCPCH-TX-Power.c
	PrimaryCPICH-Info.c
	PrimaryCPICH-TX-Power.c
	PrimaryScramblingCode.c
	ProtocolErrorCause.c
	ProtocolErrorIndicator.c
	ProtocolErrorIndicatorWithMoreInfo.c
	ProtocolErrorInformation.c
	ProtocolErrorMoreInformation.c
	PuncturingLimit.c
	Q-HCS.c
	Q-Hyst-S-Fine.c
	Q-Hyst-S.c
	Q-OffsetS-N.c
	Q-QualMin.c
	Q-RxlevMin.c
	QualityEventResults.c
	QualityMeasuredResults.c
	QualityMeasurement.c
	QualityReportCriteria.c
	QualityReportingCriteria.c
	QualityReportingCriteriaSingle.c
	QualityReportingQuantity.c
	QualityTarget.c
	RAB-Identity.c
	RAB-Info-Post.c
	RAB-Info-r6-ext.c
	RAB-Info-r6.c
	RAB-Info.c
	RAB-InformationList-r6.c
	RAB-InformationList.c
	RAB-InformationReconfig.c
	RAB-InformationReconfigList.c
	RAB-InformationSetup-r4.c
	RAB-InformationSetup-r5.c
	RAB-InformationSetup-r6-ext.c
	RAB-InformationSetup-r6.c
	RAB-InformationSetup.c
	RAB-InformationSetupList-r4.c
	RAB-InformationSetupList-r5.c
	RAB-InformationSetupList-r6-ext.c
	RAB-InformationSetupList-r6.c
	RAB-InformationSetupList.c
	RACH-TransmissionParameters.c
	RAI.c
	RAT-FDD-Info.c
	RAT-FDD-InfoList.c
	RAT-Identifier.c
	RAT-TDD-Info.c
	RAT-TDD-InfoList.c
	RAT-Type.c
	RAT.c
	RB-ActivationTimeInfo.c
	RB-ActivationTimeInfoList.c
	RB-COUNT-C-Information.c
	RB-COUNT-C-InformationList.c
	RB-COUNT-C-MSB-Information.c
	RB-COUNT-C-MSB-InformationList.c
	RB-Identity.c
	RB-IdentityList.c
	RB-InformationAffected-r5.c
	RB-InformationAffected-r6.c
	RB-InformationAffected.c
	RB-InformationAffectedList-r5.c
	RB-InformationAffectedList-r6.c
	RB-InformationAffectedList.c
	RB-InformationChanged-r6.c
	RB-InformationChangedList-r6.c
	RB-InformationReconfig-r4.c
	RB-InformationReconfig-r5.c
	RB-InformationReconfig-r6.c
	RB-InformationReconfig.c
	RB-InformationReconfigList-r4.c
	RB-InformationReconfigList-r5.c
	RB-InformationReconfigList-r6.c
	RB-InformationReconfigList.c
	RB-InformationReleaseList.c
	RB-InformationSetup-r4.c
	RB-InformationSetup-r5.c
	RB-InformationSetup-r6.c
	RB-InformationSetup.c
	RB-InformationSetupList-r4.c
	RB-InformationSetupList-r5.c
	RB-InformationSetupList-r6.c
	RB-InformationSetupList.c
	RB-MappingInfo-r5.c
	RB-MappingInfo-r6.c
	RB-MappingInfo.c
	RB-MappingOption-r5.c
	RB-MappingOption-r6.c
	RB-MappingOption.c
	RB-PDCPContextRelocation.c
	RB-PDCPContextRelocationList.c
	RB-StopContinue.c
	RB-WithPDCP-Info.c
	RB-WithPDCP-InfoList.c
	RF-CapabBandFDDComp.c
	RF-CapabBandListFDDComp-ext.c
	RF-CapabBandListFDDComp.c
	RF-Capability-r4-ext.c
	RF-Capability-r4.c
	RF-Capability-r7.c
	RF-Capability.c
	RF-CapabilityComp-r7.c
	RF-CapabilityComp.c
	RFC2507-Info.c
	RFC3095-Context-List.c
	RFC3095-ContextInfo-r5.c
	RFC3095-ContextInfo.c
	RFC3095-ContextInfoList-r5.c
	RFC3095-Info-r4.c
	RL-AdditionInfoList.c
	RL-AdditionInformation-r6.c
	RL-AdditionInformation.c
	RL-AdditionInformationList-r6.c
	RL-AdditionInformationList.c
	RL-IdentifierList.c
	RL-InformationLists.c
	RL-RemovalInformationList.c
	RLC-BuffersPayload.c
	RLC-Capability-r5-ext.c
	RLC-Capability-r5.c
	RLC-Capability.c
	RLC-Info-MCCH-r6.c
	RLC-Info-MSCH-r6.c
	RLC-Info-MTCH-r6.c
	RLC-Info-r5.c
	RLC-Info-r6.c
	RLC-Info.c
	RLC-InfoChoice-r5.c
	RLC-InfoChoice-r6.c
	RLC-InfoChoice.c
	RLC-PDU-Size.c
	RLC-PDU-SizeList.c
	RLC-SequenceNumber.c
	RLC-SizeExplicitList.c
	RLC-SizeInfo.c
	ROHC-PacketSize-r4.c
	ROHC-PacketSizeList-r4.c
	ROHC-Profile-r4.c
	ROHC-ProfileList-r4.c
	RPP.c
	RRC-ConnectionReleaseInformation.c
	RRC-FailureInfo-r3-IEs.c
	RRC-FailureInfo.c
	RRC-MessageSequenceNumber.c
	RRC-MessageSequenceNumberList.c
	RRC-StateIndicator.c
	RRC-TransactionIdentifier.c
	RRC.c
	RRCConnectionReject-r3-IEs.c
	RRCConnectionReject-v690ext-IEs.c
	RRCConnectionReject.c
	RRCConnectionRelease-CCCH-r3-IEs.c
	RRCConnectionRelease-CCCH-r4-IEs.c
	RRCConnectionRelease-CCCH-r5-IEs.c
	RRCConnectionRelease-CCCH-v690ext-IEs.c
	RRCConnectionRelease-CCCH.c
	RRCConnectionRelease-r3-IEs.c
	RRCConnectionRelease-r4-IEs.c
	RRCConnectionRelease-v690ext-IEs.c
	RRCConnectionRelease.c
	RRCConnectionReleaseComplete.c
	RRCConnectionRequest-v3d0ext-IEs.c
	RRCConnectionRequest-v4b0ext-IEs.c
	RRCConnectionRequest-v590ext-IEs.c
	RRCConnectionRequest-v690ext-IEs.c
	RRCConnectionRequest.c
	RRCConnectionSetup-r3-IEs.c
	RRCConnectionSetup-r4-IEs.c
	RRCConnectionSetup-r5-IEs.c
	RRCConnectionSetup-r6-IEs.c
	RRCConnectionSetup-r7-IEs.c
	RRCConnectionSetup-v4b0ext-IEs.c
	RRCConnectionSetup-v590ext-IEs.c
	RRCConnectionSetup-v690ext-IEs.c
	RRCConnectionSetup-v7xyext-IEs.c
	RRCConnectionSetup.c
	RRCConnectionSetupComplete-r3-add-ext-IEs.c
	RRCConnectionSetupComplete-v370ext.c
	RRCConnectionSetupComplete-v380ext-IEs.c
	RRCConnectionSetupComplete-v3a0ext-IEs.c
	RRCConnectionSetupComplete-v3g0ext-IEs.c
	RRCConnectionSetupComplete-v4b0ext-IEs.c
	RRCConnectionSetupComplete-v590ext-IEs.c
	RRCConnectionSetupComplete-v5c0ext-IEs.c
	RRCConnectionSetupComplete-v650ext-IEs.c
	RRCConnectionSetupComplete-v680ext-IEs.c
	RRCConnectionSetupComplete-v690ext-IEs.c
	RRCConnectionSetupComplete-v7xyext-IEs.c
	RRCConnectionSetupComplete.c
	RRCStatus.c
	RadioBearerReconfiguration-r3-IEs.c
	RadioBearerReconfiguration-r4-IEs.c
	RadioBearerReconfiguration-r5-IEs.c
	RadioBearerReconfiguration-r6-IEs.c
	RadioBearerReconfiguration-r7-IEs.c
	RadioBearerReconfiguration-v3a0ext.c
	RadioBearerReconfiguration-v4b0ext-IEs.c
	RadioBearerReconfiguration-v590ext-IEs.c
	RadioBearerReconfiguration-v5d0ext-IEs.c
	RadioBearerReconfiguration-v690ext-IEs.c
	RadioBearerReconfiguration.c
	RadioBearerReconfigurationComplete-v7xyext-IEs.c
	RadioBearerReconfigurationComplete.c
	RadioBearerReconfigurationFailure.c
	RadioBearerRelease-r3-IEs.c
	RadioBearerRelease-r4-IEs.c
	RadioBearerRelease-r5-IEs.c
	RadioBearerRelease-r6-IEs.c
	RadioBearerRelease-r7-IEs.c
	RadioBearerRelease-v3a0ext.c
	RadioBearerRelease-v4b0ext-IEs.c
	RadioBearerRelease-v590ext-IEs.c
	RadioBearerRelease-v690ext-IEs.c
	RadioBearerRelease.c
	RadioBearerReleaseComplete-v7xyext-IEs.c
	RadioBearerReleaseComplete.c
	RadioBearerReleaseFailure.c
	RadioBearerSetup-r3-IEs.c
	RadioBearerSetup-r4-IEs.c
	RadioBearerSetup-r5-IEs.c
	RadioBearerSetup-r6-IEs.c
	RadioBearerSetup-r7-IEs.c
	RadioBearerSetup-v3a0ext.c
	RadioBearerSetup-v4b0ext-IEs.c
	RadioBearerSetup-v590ext-IEs.c
	RadioBearerSetup-v5d0ext-IEs.c
	RadioBearerSetup-v690ext-IEs.c
	RadioBearerSetup.c
	RadioBearerSetupComplete-v7xyext-IEs.c
	RadioBearerSetupComplete.c
	RadioBearerSetupFailure.c
	RadioFrequencyBandFDD.c
	RadioFrequencyBandFDD2.c
	RadioFrequencyBandGSM.c
	RadioFrequencyBandTDD.c
	RadioFrequencyBandTDDList.c
	RateMatchingAttribute.c
	Rb-timer-indicator.c
	Re-EstablishmentTimer.c
	ReceivedMessageType.c
	ReceivingWindowSize.c
	RedirectionInfo-r6.c
	RedirectionInfo.c
	ReducedScramblingCodeNumber.c
	ReferenceCellPosition.c
	ReferenceLocation.c
	ReferenceTFC-ID.c
	ReferenceTimeDifferenceToCell.c
	RejectionCause.c
	ReleaseCause.c
	RemovedInterFreqCellList.c
	RemovedInterRATCellList.c
	RemovedIntraFreqCellList.c
	RepPerLengthOffset-MICH.c
	RepPerLengthOffset-PICH.c
	RepetitionPeriodAndLength.c
	RepetitionPeriodLengthAndOffset.c
	ReplacedPDSCH-CodeInfo.c
	ReplacedPDSCH-CodeInfoList.c
	ReplacementActivationThreshold.c
	ReportDeactivationThreshold.c
	ReportingAmount.c
	ReportingCellStatus.c
	ReportingCellStatusOpt.c
	ReportingInfoForCellDCH-LCR-r4.c
	ReportingInfoForCellDCH.c
	ReportingInterval.c
	ReportingIntervalLong.c
	ReportingRange.c
	ReservedIndicator.c
	RestrictedTrCH-InfoList.c
	RestrictedTrCH.c
	RestrictedTrChInfo.c
	RestrictedTrChInfoList.c
	RoutingAreaCode.c
	RoutingParameter.c
	Rplmn-Information-r4.c
	Rplmn-Information.c
	S-Field.c
	S-RNTI-2.c
	S-RNTI.c
	S-SearchQual.c
	S-SearchRXLEV.c
	SCCPCH-ChannelisationCode-VHCR.c
	SCCPCH-ChannelisationCode.c
	SCCPCH-ChannelisationCodeList-VHCR.c
	SCCPCH-ChannelisationCodeList.c
	SCCPCH-InfoForFACH-r4.c
	SCCPCH-InfoForFACH.c
	SCCPCH-SystemInformation-LCR-r4-ext.c
	SCCPCH-SystemInformation-MBMS-r6.c
	SCCPCH-SystemInformation-MBMS-r7.c
	SCCPCH-SystemInformation-r7.c
	SCCPCH-SystemInformation.c
	SCCPCH-SystemInformationList-LCR-r4-ext.c
	SCCPCH-SystemInformationList-r7.c
	SCCPCH-SystemInformationList.c
	SF-PDSCH.c
	SF-PRACH.c
	SF256-AndCodeNumber.c
	SF512-AndCodeNumber.c
	SF512-AndPilot.c
	SFN-Offset-Validity.c
	SFN-Prime.c
	SFN-SFN-Drift.c
	SFN-SFN-OTD-Type.c
	SFN-SFN-ObsTimeDifference.c
	SFN-SFN-ObsTimeDifference1.c
	SFN-SFN-ObsTimeDifference2.c
	SFN-SFN-RelTimeDifference1.c
	SFN-TOW-Uncertainty.c
	SFN-TimeInfo.c
	SIB-Data-fixed.c
	SIB-Data-variable.c
	SIB-ReferenceList.c
	SIB-ReferenceListFACH.c
	SIB-Type.c
	SIB-TypeAndTag.c
	SIBOccurIdentity.c
	SIBOccurValueTag.c
	SIBOccurrenceIdentityAndValueTag.c
	SIBSb-ReferenceList.c
	SIBSb-TypeAndTag.c
	SID.c
	SIR-MeasurementList.c
	SIR-MeasurementResults.c
	SIR-TFCS-List.c
	SIR-TFCS.c
	SIR-TimeslotList.c
	SIR.c
	SRB-InformationSetup-r5.c
	SRB-InformationSetup-r6.c
	SRB-InformationSetup.c
	SRB-InformationSetupList-r5.c
	SRB-InformationSetupList-r6.c
	SRB-InformationSetupList.c
	SRB-InformationSetupList2-r6.c
	SRB-InformationSetupList2.c
	SRB-SpecificIntegrityProtInfo.c
	SRB-SpecificIntegrityProtInfoList.c
	SRB-delay.c
	SRNC-Identity.c
	SRNC-RelocationInfo-r3-IEs.c
	SRNC-RelocationInfo-r3.c
	SRNC-RelocationInfo-r4-IEs.c
	SRNC-RelocationInfo-r5-IEs.c
	SRNC-RelocationInfo-r6-IEs.c
	SRNC-RelocationInfo-v380ext-IEs.c
	SRNC-RelocationInfo-v390ext-IEs.c
	SRNC-RelocationInfo-v3a0ext-IEs.c
	SRNC-RelocationInfo-v3b0ext-IEs.c
	SRNC-RelocationInfo-v3c0ext-IEs.c
	SRNC-RelocationInfo-v3d0ext-IEs.c
	SRNC-RelocationInfo-v3g0ext-IEs.c
	SRNC-RelocationInfo-v3h0ext-IEs.c
	SRNC-RelocationInfo-v4b0ext-IEs.c
	SRNC-RelocationInfo-v4d0ext-IEs.c
	SRNC-RelocationInfo-v590ext-IEs.c
	SRNC-RelocationInfo-v5a0ext-IEs.c
	SRNC-RelocationInfo-v5b0ext-IEs.c
	SRNC-RelocationInfo-v5c0ext-IEs.c
	SRNC-RelocationInfo-v690ext-IEs.c
	SRNC-RelocationInfo-v7xyext-IEs.c
	SSDT-CellIdentity.c
	SSDT-Information-r4.c
	SSDT-Information.c
	SSDT-UL.c
	START-Value.c
	STARTList.c
	STARTList2.c
	STARTSingle.c
	SYNC-UL-Info-r4.c
	SYNC-UL-Procedure-r4.c
	SatData.c
	SatDataList.c
	SatID.c
	SatelliteStatus.c
	SchedulingInformation.c
	SchedulingInformationSIB.c
	SchedulingInformationSIBSb.c
	ScramblingCodeChange.c
	ScramblingCodeType.c
	SecondInterleavingMode.c
	SecondaryCCPCH-Info-LCR-r4-ext.c
	SecondaryCCPCH-Info-r4.c
	SecondaryCCPCH-Info-r7.c
	SecondaryCCPCH-Info.c
	SecondaryCCPCHInfo-MBMS-r6.c
	SecondaryCCPCHInfo-MBMS-r7.c
	SecondaryCPICH-Info.c
	SecondaryScramblingCode.c
	SecurityCapability.c
	SecurityModeCommand-r3-IEs.c
	SecurityModeCommand.c
	SecurityModeComplete.c
	SecurityModeFailure.c
	SegCount.c
	SegmentIndex.c
	SemistaticTF-Information.c
	Serving-HSDSCH-CellInformation.c
	SibOFF-List.c
	SibOFF.c
	SignalledGainFactors.c
	SignallingConnectionRelease-r3-IEs.c
	SignallingConnectionRelease.c
	SignallingConnectionReleaseIndication.c
	SimultaneousSCCPCH-DPCH-Reception.c
	SpecialBurstScheduling.c
	SpeedDependentScalingFactor.c
	SplitTFCI-Signalling.c
	SplitType.c
	SpreadingFactor.c
	StateOfRRC-Procedure.c
	StateOfRRC.c
	StoredCompressedModeInfo.c
	StoredTGP-Sequence.c
	StoredTGP-SequenceList.c
	SubFrame1Reserved.c
	SubsequentSegment.c
	SupportOfDedicatedPilotsForChEstimation.c
	SynchronisationParameters-r4.c
	SysInfoType1-v3a0ext-IEs.c
	SysInfoType1.c
	SysInfoType10.c
	SysInfoType11-v4b0ext-IEs.c
	SysInfoType11-v590ext-IEs.c
	SysInfoType11-v690ext-IEs.c
	SysInfoType11.c
	SysInfoType12-v4b0ext-IEs.c
	SysInfoType12-v590ext-IEs.c
	SysInfoType12-v690ext-IEs.c
	SysInfoType12.c
	SysInfoType13-1.c
	SysInfoType13-2.c
	SysInfoType13-3.c
	SysInfoType13-4.c
	SysInfoType13-v3a0ext-IEs.c
	SysInfoType13-v4b0ext-IEs.c
	SysInfoType13-v7xyext-IEs.c
	SysInfoType13.c
	SysInfoType14.c
	SysInfoType15-1.c
	SysInfoType15-2.c
	SysInfoType15-3.c
	SysInfoType15-4-v3a0ext.c
	SysInfoType15-4-v4b0ext.c
	SysInfoType15-4.c
	SysInfoType15-5-v3a0ext.c
	SysInfoType15-5.c
	SysInfoType15-v4b0ext-IEs.c
	SysInfoType15.c
	SysInfoType16.c
	SysInfoType17-v4b0ext-IEs.c
	SysInfoType17-v590ext-IEs.c
	SysInfoType17-v7xyext-IEs.c
	SysInfoType17.c
	SysInfoType18.c
	SysInfoType2.c
	SysInfoType3-v4b0ext-IEs.c
	SysInfoType3-v590ext.c
	SysInfoType3-v5c0ext-IEs.c
	SysInfoType3-v670ext.c
	SysInfoType3.c
	SysInfoType4-v4b0ext-IEs.c
	SysInfoType4-v590ext.c
	SysInfoType4-v5b0ext-IEs.c
	SysInfoType4-v5c0ext-IEs.c
	SysInfoType4.c
	SysInfoType5-v4b0ext-IEs.c
	SysInfoType5-v590ext-IEs.c
	SysInfoType5-v650ext-IEs.c
	SysInfoType5-v680ext-IEs.c
	SysInfoType5-v690ext-IEs.c
	SysInfoType5-v7xyext-IEs.c
	SysInfoType5.c
	SysInfoType5bis.c
	SysInfoType6-v4b0ext-IEs.c
	SysInfoType6-v590ext-IEs.c
	SysInfoType6-v650ext-IEs.c
	SysInfoType6-v690ext-IEs.c
	SysInfoType6-v7xyext-IEs.c
	SysInfoType6.c
	SysInfoType7.c
	SysInfoType8.c
	SysInfoType9.c
	SysInfoTypeSB1.c
	SysInfoTypeSB2.c
	SystemInformation-BCH.c
	SystemInformation-FACH.c
	SystemInformationChangeIndication.c
	SystemSpecificCapUpdateReq-r5.c
	SystemSpecificCapUpdateReq-v590ext.c
	SystemSpecificCapUpdateReq.c
	SystemSpecificCapUpdateReqList-r5.c
	SystemSpecificCapUpdateReqList.c
	T-300.c
	T-301.c
	T-302.c
	T-304.c
	T-305.c
	T-307.c
	T-308.c
	T-309.c
	T-310.c
	T-311.c
	T-312.c
	T-313.c
	T-314.c
	T-315.c
	T-316.c
	T-317.c
	T-318.c
	T-ADVinfo.c
	T-Barred.c
	T-CPCH.c
	T-CRMax.c
	T-CRMaxHyst.c
	T-Reselection-S-Fine.c
	T-Reselection-S.c
	T1-ReleaseTimer.c
	TDD-FPACH-CCode16-r4.c
	TDD-PICH-CCode.c
	TDD-PRACH-CCode-LCR-r4.c
	TDD-PRACH-CCode16.c
	TDD-PRACH-CCode8.c
	TDD-PRACH-CCodeList.c
	TDD-UL-Interference.c
	TDD-UMTS-Frequency-List.c
	TDD768-PICH-CCode.c
	TDD768-PRACH-CCode16.c
	TDD768-PRACH-CCode32.c
	TDD768-PRACH-CCode8.c
	TDD768-PRACH-CCodeList.c
	TFC-ControlDuration.c
	TFC-Subset.c
	TFC-SubsetList.c
	TFC-Value.c
	TFCI-Coding.c
	TFCI-Field2-Information.c
	TFCI-Range.c
	TFCI-RangeList.c
	TFCS-Identity.c
	TFCS-IdentityPlain.c
	TFCS-InfoForDSCH.c
	TFCS-ReconfAdd-foo12.c
	TFCS-ReconfAdd-foo16.c
	TFCS-ReconfAdd-foo2.c
	TFCS-ReconfAdd-foo24.c
	TFCS-ReconfAdd-foo4.c
	TFCS-ReconfAdd-foo6.c
	TFCS-ReconfAdd-foo8.c
	TFCS-ReconfAdd.c
	TFCS-Removal.c
	TFCS-RemovalList.c
	TFCS.c
	TGCFN.c
	TGD.c
	TGL.c
	TGMP.c
	TGP-Sequence.c
	TGP-SequenceList.c
	TGP-SequenceShort.c
	TGPL.c
	TGPRC.c
	TGPS-ConfigurationParams.c
	TGPS-Reconfiguration-CFN.c
	TGPSI.c
	TGSN.c
	TM-SignallingInfo.c
	TMSI-DS-41.c
	TMSI-GSM-MAP.c
	TMSI-and-LAI-GSM-MAP.c
	TPC-Combination-Info.c
	TPC-CombinationIndex.c
	TPC-CombinationInfoList.c
	TPC-CommandTargetRate.c
	TPC-StepSizeFDD.c
	TPC-StepSizeTDD.c
	TX-DiversityMode.c
	TX-InterruptionAfterTrigger.c
	TargetRNC-ToSourceRNC-Container.c
	TemporaryOffset1.c
	TemporaryOffset2.c
	TemporaryOffsetList.c
	ThreholdNonUsedFrequency-deltaList.c
	Threshold-r6.c
	Threshold.c
	ThresholdPositionChange.c
	ThresholdSFN-GPS-TOW.c
	ThresholdSFN-SFN-Change.c
	ThresholdUsedFrequency-r6.c
	ThresholdUsedFrequency.c
	TimeDurationBeforeRetry.c
	TimeInfo.c
	TimeInterval.c
	TimeToTrigger.c
	TimerDAR-r6.c
	TimerDiscard.c
	TimerEPC.c
	TimerMRW.c
	TimerOSD-r6.c
	TimerPoll.c
	TimerPollPeriodic.c
	TimerPollProhibit.c
	TimerRST.c
	TimerStatusPeriodic.c
	TimerStatusProhibit.c
	TimeslotISCP-List.c
	TimeslotISCP.c
	TimeslotInfo-LCR-r4.c
	TimeslotInfo.c
	TimeslotInfoList-LCR-r4.c
	TimeslotInfoList-r4.c
	TimeslotInfoList.c
	TimeslotList-r4.c
	TimeslotList.c
	TimeslotListWithISCP.c
	TimeslotNumber-LCR-r4.c
	TimeslotNumber-PRACH-LCR-r4.c
	TimeslotNumber.c
	TimeslotSync2.c
	TimeslotWithISCP.c
	TimingMaintainedSynchInd.c
	TimingOffset.c
	ToTargetRNC-Container.c
	TotalRLC-AM-BufferSize-r5-ext.c
	TotalRLC-AM-BufferSize-r5.c
	TotalRLC-AM-BufferSize.c
	TrafficVolumeEventParam.c
	TrafficVolumeEventResults.c
	TrafficVolumeEventType.c
	TrafficVolumeMeasQuantity.c
	TrafficVolumeMeasSysInfo.c
	TrafficVolumeMeasuredResults.c
	TrafficVolumeMeasuredResultsList.c
	TrafficVolumeMeasurement.c
	TrafficVolumeMeasurementObjectList.c
	TrafficVolumeReportCriteria.c
	TrafficVolumeReportCriteriaSysInfo.c
	TrafficVolumeReportingCriteria.c
	TrafficVolumeReportingQuantity.c
	TrafficVolumeThreshold.c
	TransChCriteria.c
	TransChCriteriaList.c
	TransferMode.c
	TransmissionProbability.c
	TransmissionRLC-Discard.c
	TransmissionTimeInterval.c
	TransmissionTimeValidity.c
	TransmissionWindowSize.c
	TransmittedPowerThreshold.c
	TransportChannelCapability.c
	TransportChannelIdentity.c
	TransportChannelIdentityDCHandDSCH.c
	TransportChannelReconfiguration-r3-IEs.c
	TransportChannelReconfiguration-r4-IEs.c
	TransportChannelReconfiguration-r5-IEs.c
	TransportChannelReconfiguration-r6-IEs.c
	TransportChannelReconfiguration-r7-IEs.c
	TransportChannelReconfiguration-v3a0ext.c
	TransportChannelReconfiguration-v4b0ext-IEs.c
	TransportChannelReconfiguration-v590ext-IEs.c
	TransportChannelReconfiguration-v690ext-IEs.c
	TransportChannelReconfiguration.c
	TransportChannelReconfigurationComplete-v7xyext-IEs.c
	TransportChannelReconfigurationComplete.c
	TransportChannelReconfigurationFailure.c
	TransportFormatCombinationControl.c
	TransportFormatCombinationControlFailure.c
	TransportFormatSet-LCR.c
	TransportFormatSet.c
	TreconfirmAbort.c
	TreselectionScalingFactor.c
	TriggeringCondition1.c
	TriggeringCondition2.c
	TurboSupport.c
	TxRxFrequencySeparation.c
	U-RNTI-Group.c
	U-RNTI-Short.c
	U-RNTI.c
	UARFCN.c
	UCSM-Info.c
	UDRE.c
	UE-6AB-Event.c
	UE-6FG-Event.c
	UE-AutonomousUpdateMode.c
	UE-CapabilityContainer-IEs.c
	UE-ConnTimersAndConstants-r5.c
	UE-ConnTimersAndConstants-v3a0ext.c
	UE-ConnTimersAndConstants.c
	UE-IdleTimersAndConstants-v3a0ext.c
	UE-IdleTimersAndConstants.c
	UE-InternalEventParam.c
	UE-InternalEventParamList.c
	UE-InternalEventResults.c
	UE-InternalMeasQuantity.c
	UE-InternalMeasuredResults-LCR-r4.c
	UE-InternalMeasuredResults-r7.c
	UE-InternalMeasuredResults.c
	UE-InternalMeasurement-r4.c
	UE-InternalMeasurement.c
	UE-InternalMeasurementSysInfo.c
	UE-InternalReportCriteria.c
	UE-InternalReportingCriteria.c
	UE-InternalReportingQuantity-r4.c
	UE-InternalReportingQuantity.c
	UE-MeasurementQuantity.c
	UE-MultiModeRAT-Capability-r5.c
	UE-MultiModeRAT-Capability.c
	UE-Positioning-Accuracy.c
	UE-Positioning-Capability-r4.c
	UE-Positioning-Capability.c
	UE-Positioning-CipherParameters.c
	UE-Positioning-Error.c
	UE-Positioning-ErrorCause.c
	UE-Positioning-EventParam.c
	UE-Positioning-EventParamList.c
	UE-Positioning-EventSpecificInfo.c
	UE-Positioning-GPS-AcquisitionAssistance.c
	UE-Positioning-GPS-AdditionalAssistanceDataRequest.c
	UE-Positioning-GPS-Almanac.c
	UE-Positioning-GPS-AssistanceData.c
	UE-Positioning-GPS-DGPS-Corrections.c
	UE-Positioning-GPS-IonosphericModel.c
	UE-Positioning-GPS-MeasurementResults.c
	UE-Positioning-GPS-NavModelAddDataReq.c
	UE-Positioning-GPS-NavigationModel.c
	UE-Positioning-GPS-ReferenceCellInfo.c
	UE-Positioning-GPS-ReferenceTime.c
	UE-Positioning-GPS-UTC-Model.c
	UE-Positioning-IPDL-Parameters-TDD-r4-ext.c
	UE-Positioning-IPDL-Parameters-TDDList-r4-ext.c
	UE-Positioning-IPDL-Parameters-r4.c
	UE-Positioning-IPDL-Parameters.c
	UE-Positioning-LastKnownPos.c
	UE-Positioning-MeasuredResults-v390ext.c
	UE-Positioning-MeasuredResults.c
	UE-Positioning-Measurement-r4.c
	UE-Positioning-Measurement-v390ext.c
	UE-Positioning-Measurement-v7xyext.c
	UE-Positioning-Measurement.c
	UE-Positioning-MeasurementEventResults.c
	UE-Positioning-MeasurementInterval.c
	UE-Positioning-MethodType.c
	UE-Positioning-OTDOA-AssistanceData-UEB.c
	UE-Positioning-OTDOA-AssistanceData-r4.c
	UE-Positioning-OTDOA-AssistanceData-r4ext.c
	UE-Positioning-OTDOA-AssistanceData.c
	UE-Positioning-OTDOA-Measurement-v390ext.c
	UE-Positioning-OTDOA-Measurement.c
	UE-Positioning-OTDOA-NeighbourCellInfo-UEB.c
	UE-Positioning-OTDOA-NeighbourCellInfo-r4.c
	UE-Positioning-OTDOA-NeighbourCellInfo.c
	UE-Positioning-OTDOA-NeighbourCellList-UEB.c
	UE-Positioning-OTDOA-NeighbourCellList-r4.c
	UE-Positioning-OTDOA-NeighbourCellList.c
	UE-Positioning-OTDOA-Quality.c
	UE-Positioning-OTDOA-ReferenceCellInfo-UEB.c
	UE-Positioning-OTDOA-ReferenceCellInfo-r4.c
	UE-Positioning-OTDOA-ReferenceCellInfo.c
	UE-Positioning-PositionEstimateInfo.c
	UE-Positioning-ReportCriteria.c
	UE-Positioning-ReportingQuantity-r4.c
	UE-Positioning-ReportingQuantity-v390ext.c
	UE-Positioning-ReportingQuantity-v7xyext.c
	UE-Positioning-ReportingQuantity.c
	UE-Positioning-ResponseTime.c
	UE-PositioningCapabilityExt-v380.c
	UE-PositioningCapabilityExt-v3a0.c
	UE-PositioningCapabilityExt-v3g0.c
	UE-PowerClass.c
	UE-PowerClassExt.c
	UE-RX-TX-ReportEntry.c
	UE-RX-TX-ReportEntryList.c
	UE-RX-TX-TimeDifferenceThreshold.c
	UE-RX-TX-TimeDifferenceType1.c
	UE-RX-TX-TimeDifferenceType2.c
	UE-RX-TX-TimeDifferenceType2Info.c
	UE-RadioAccessCapabBandFDD-ext.c
	UE-RadioAccessCapabBandFDD.c
	UE-RadioAccessCapabBandFDD2.c
	UE-RadioAccessCapabBandFDDList-ext.c
	UE-RadioAccessCapabBandFDDList.c
	UE-RadioAccessCapabBandFDDList2.c
	UE-RadioAccessCapability-r4.c
	UE-RadioAccessCapability-r5.c
	UE-RadioAccessCapability-r6.c
	UE-RadioAccessCapability-r7.c
	UE-RadioAccessCapability-v370ext.c
	UE-RadioAccessCapability-v380ext.c
	UE-RadioAccessCapability-v3a0ext.c
	UE-RadioAccessCapability-v3g0ext.c
	UE-RadioAccessCapability-v4b0ext.c
	UE-RadioAccessCapability-v590ext.c
	UE-RadioAccessCapability-v5c0ext.c
	UE-RadioAccessCapability-v650ext.c
	UE-RadioAccessCapability-v680ext.c
	UE-RadioAccessCapability-v690ext.c
	UE-RadioAccessCapability-v7xyext.c
	UE-RadioAccessCapability.c
	UE-RadioAccessCapabilityComp-ext.c
	UE-RadioAccessCapabilityComp-r7.c
	UE-RadioAccessCapabilityComp.c
	UE-RadioAccessCapabilityComp2.c
	UE-RadioAccessCapabilityInfo.c
	UE-SecurityInformation.c
	UE-SecurityInformation2.c
	UE-TransmittedPower.c
	UE-TransmittedPowerTDD-List.c
	UECapabilityEnquiry-r3-IEs.c
	UECapabilityEnquiry-v4b0ext-IEs.c
	UECapabilityEnquiry-v590ext-IEs.c
	UECapabilityEnquiry-v7xyext-IEs.c
	UECapabilityEnquiry.c
	UECapabilityInformation-r3-add-ext-IEs.c
	UECapabilityInformation-v370ext.c
	UECapabilityInformation-v380ext-IEs.c
	UECapabilityInformation-v3a0ext-IEs.c
	UECapabilityInformation-v4b0ext.c
	UECapabilityInformation-v590ext.c
	UECapabilityInformation-v5c0ext.c
	UECapabilityInformation-v650ext-IEs.c
	UECapabilityInformation-v680ext-IEs.c
	UECapabilityInformation-v690ext-IEs.c
	UECapabilityInformation-v7xyext-IEs.c
	UECapabilityInformation.c
	UECapabilityInformationConfirm-r3-IEs.c
	UECapabilityInformationConfirm.c
	UESpecificBehaviourInformation1idle.c
	UESpecificBehaviourInformation1interRAT.c
	UL-AM-RLC-Mode.c
	UL-AddReconfTransChInfoList-r6.c
	UL-AddReconfTransChInfoList.c
	UL-AddReconfTransChInformation-r6.c
	UL-AddReconfTransChInformation.c
	UL-CCCH-Message.c
	UL-CCCH-MessageType.c
	UL-CCTrCH-r4.c
	UL-CCTrCH-r7.c
	UL-CCTrCH.c
	UL-CCTrCHList-r4.c
	UL-CCTrCHList-r7.c
	UL-CCTrCHList.c
	UL-CCTrCHListToRemove.c
	UL-CCTrChTPCList.c
	UL-ChannelRequirement-r4.c
	UL-ChannelRequirement-r5.c
	UL-ChannelRequirement.c
	UL-ChannelRequirementWithCPCH-SetID-r4.c
	UL-ChannelRequirementWithCPCH-SetID-r5.c
	UL-ChannelRequirementWithCPCH-SetID.c
	UL-CommonTransChInfo-r4.c
	UL-CommonTransChInfo.c
	UL-CompressedModeMethod.c
	UL-ControlledTrChList.c
	UL-CounterSynchronisationInfo.c
	UL-DCCH-Message.c
	UL-DCCH-MessageType.c
	UL-DL-Mode.c
	UL-DPCCH-SlotFormat.c
	UL-DPCH-Info-r4.c
	UL-DPCH-Info-r5.c
	UL-DPCH-Info-r6.c
	UL-DPCH-Info-r7.c
	UL-DPCH-Info.c
	UL-DPCH-InfoPostFDD.c
	UL-DPCH-InfoPostTDD-LCR-r4.c
	UL-DPCH-InfoPostTDD.c
	UL-DPCH-InfoPredef.c
	UL-DPCH-PowerControlInfo-r4.c
	UL-DPCH-PowerControlInfo-r5.c
	UL-DPCH-PowerControlInfo-r6.c
	UL-DPCH-PowerControlInfo-r7.c
	UL-DPCH-PowerControlInfo.c
	UL-DPCH-PowerControlInfoPostFDD.c
	UL-DPCH-PowerControlInfoPostTDD-LCR-r4.c
	UL-DPCH-PowerControlInfoPostTDD.c
	UL-DPCH-PowerControlInfoPredef.c
	UL-DeletedTransChInfoList-r6.c
	UL-DeletedTransChInfoList.c
	UL-EDCH-Information-r6.c
	UL-Interference.c
	UL-LogicalChannelMapping-r6.c
	UL-LogicalChannelMapping.c
	UL-LogicalChannelMappingList-r6.c
	UL-LogicalChannelMappingList.c
	UL-LogicalChannelMappings-r6.c
	UL-LogicalChannelMappings.c
	UL-PhysChCapabilityFDD-r6.c
	UL-PhysChCapabilityFDD.c
	UL-PhysChCapabilityTDD-LCR-r4.c
	UL-PhysChCapabilityTDD.c
	UL-RFC3095-Context.c
	UL-RFC3095-r4.c
	UL-RLC-Mode.c
	UL-SHCCH-Message.c
	UL-SHCCH-MessageType.c
	UL-ScramblingCode.c
	UL-SynchronisationParameters-r4.c
	UL-TM-RLC-Mode.c
	UL-TS-ChannelisationCode-VHCR.c
	UL-TS-ChannelisationCode.c
	UL-TS-ChannelisationCodeList-VHCR.c
	UL-TS-ChannelisationCodeList-r7.c
	UL-TS-ChannelisationCodeList.c
	UL-TargetSIR.c
	UL-TimingAdvance-VHCR.c
	UL-TimingAdvance.c
	UL-TimingAdvanceControl-LCR-r4.c
	UL-TimingAdvanceControl-r4.c
	UL-TimingAdvanceControl-r7.c
	UL-TimingAdvanceControl.c
	UL-TrCH-Identity.c
	UL-TrCH-Type.c
	UL-TransChCapability.c
	UL-TransportChannelIdentity-r6.c
	UL-TransportChannelIdentity.c
	UL-TransportChannelType.c
	UL-UM-RLC-Mode.c
	UM-RLC-DuplAvoid-Reord-Info-r6.c
	UM-RLC-OutOSeqDelivery-Info-r6.c
	URA-Identity.c
	URA-IdentityList.c
	URA-UpdateCause.c
	URAUpdate.c
	URAUpdateConfirm-CCCH-r3-IEs.c
	URAUpdateConfirm-CCCH.c
	URAUpdateConfirm-r3-IEs.c
	URAUpdateConfirm-r5-IEs.c
	URAUpdateConfirm-v690ext-IEs.c
	URAUpdateConfirm.c
	USCH-TransportChannelsInfo-foo.c
	USCH-TransportChannelsInfo.c
	UTRA-CarrierRSSI.c
	UTRAN-DRX-CycleLengthCoefficient.c
	UTRAN-GPS-DriftRate.c
	UTRAN-GPSReferenceTime.c
	UTRAN-GPSReferenceTimeResult.c
	UTRANMobilityInformation-r3-IEs.c
	UTRANMobilityInformation-r5-IEs.c
	UTRANMobilityInformation-v3a0ext-IEs.c
	UTRANMobilityInformation.c
	UTRANMobilityInformationConfirm.c
	UTRANMobilityInformationFailure.c
	UplinkAdditionalTimeslots-LCR-r4.c
	UplinkAdditionalTimeslots-LCR-r7.c
	UplinkAdditionalTimeslots.c
	UplinkDirectTransfer-v690ext-IEs.c
	UplinkDirectTransfer.c
	UplinkPhysicalChannelControl-r3-IEs.c
	UplinkPhysicalChannelControl-r4-IEs.c
	UplinkPhysicalChannelControl-r5-IEs.c
	UplinkPhysicalChannelControl-r7-IEs.c
	UplinkPhysicalChannelControl-v4b0ext-IEs.c
	UplinkPhysicalChannelControl-v690ext-IEs.c
	UplinkPhysicalChannelControl-v6a0ext-IEs.c
	UplinkPhysicalChannelControl.c
	UplinkTimeslotsCodes-LCR-r4.c
	UplinkTimeslotsCodes-LCR-r7.c
	UplinkTimeslotsCodes-VHCR.c
	UplinkTimeslotsCodes.c
	UpperLimit.c
	UtranMobilityInformation-v690ext-IEs.c
	VarianceOfRLC-BufferPayload.c
	VelocityEstimate.c
	W.c
	WaitTime.c
	Wi-LCR.c
	WindowSizeDAR-r6.c
	WindowSizeOSD-r6.c
)
