#
# OpenBTS/cmake/features.cmake
#

# See https://github.com/Framstag/libosmscout/blob/master/cmake/features.cmake

include(CheckCXXSourceCompiles)
include(CheckPrototypeDefinition)
include(CheckCCompilerFlag)
include(CheckCXXCompilerFlag)
include(CheckTypeSize)
include(CheckFunctionExists)

if(NOT MSVC)
	check_c_compiler_flag(-faltivec HAVE_ALTIVEC)
	check_c_compiler_flag(-mavx HAVE_AVX)
	check_c_compiler_flag(-mmmx HAVE_MMX)
	option(OPENBTS_ENABLE_SSE "Enable SSE support (not working on all platforms!)" OFF)
	if(OPENBTS_ENABLE_SSE)
		check_c_compiler_flag(-msse HAVE_SSE)
		check_c_compiler_flag(-msse2 HAVE_SSE2)
		check_c_compiler_flag(-msse3 HAVE_SSE3)
		check_c_compiler_flag(-msse4.1 HAVE_SSE4_1)
		check_c_compiler_flag(-msse4.2 HAVE_SSE4_2)
		check_c_compiler_flag(-mssse3 HAVE_SSSE3)
	endif()
	if(HAVE_SSE2)
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -msse2")
	endif()
else()
	set(HAVE_ALTIVEC OFF)
	set(HAVE_AVX ON)
	set(HAVE_MMX ON)
	set(HAVE_SSE ON)
	set(HAVE_SSE2 ON)
	set(HAVE_SSE3 OFF)
	set(HAVE_SSE4_1 OFF)
	set(HAVE_SSE4_2 OFF)
	set(HAVE_SSSE3 OFF)
	if (NOT OPENBTS_PLATFORM_X64)
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:SSE2")
	endif()
endif()

if(CMAKE_COMPILER_IS_GNUCXX)
	check_cxx_compiler_flag(-fvisibility=hidden HAVE_VISIBILITY)
	if(HAVE_VISIBILITY)
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fvisibility=hidden")
	endif()
else()
	set(HAVE_VISIBILITY OFF)
endif()

# check headers exists
include(CheckIncludeFileCXX)
check_include_file(sys/stat.h HAVE_SYS_STAT_H)
check_include_file(sys/time.h HAVE_SYS_TIME_H)
check_include_file(sys/types.h HAVE_SYS_TYPES_H)
check_include_file(byteswap.h HAVE_BYTESWAP_H)
check_include_file(dlfcn.h HAVE_DLFCN_H)
check_include_file(fcntl.h HAVE_FCNTL_H)
check_include_file(inttypes.h HAVE_INTTYPES_H)
check_include_file(memory.h HAVE_MEMORY_H)
check_include_file(stdint.h HAVE_STDINT_H)
check_include_file(stdlib.h HAVE_STDLIB_H)
check_include_file(string.h HAVE_STRING_H)
check_include_file(strings.h HAVE_STRINGS_H)
check_include_file(unistd.h HAVE_UNISTD_H)

if(${HAVE_STDINT_H} AND ${HAVE_STDLIB_H} AND ${HAVE_INTTYPES_H} AND ${HAVE_STRING_H} AND ${HAVE_MEMORY_H})
	set(STDC_HEADERS ON)
else()
	set(STDC_HEADERS OFF)
endif()
